// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: wantstudy/v1/export.proto

package wantstudyv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RenderStudyExportRequest struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	StudyId                 string                 `protobuf:"bytes,1,opt,name=study_id,json=studyId,proto3" json:"study_id,omitempty"`
	ExpectedContentRevision *int64                 `protobuf:"varint,2,opt,name=expected_content_revision,json=expectedContentRevision,proto3,oneof" json:"expected_content_revision,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *RenderStudyExportRequest) Reset() {
	*x = RenderStudyExportRequest{}
	mi := &file_wantstudy_v1_export_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderStudyExportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderStudyExportRequest) ProtoMessage() {}

func (x *RenderStudyExportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wantstudy_v1_export_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderStudyExportRequest.ProtoReflect.Descriptor instead.
func (*RenderStudyExportRequest) Descriptor() ([]byte, []int) {
	return file_wantstudy_v1_export_proto_rawDescGZIP(), []int{0}
}

func (x *RenderStudyExportRequest) GetStudyId() string {
	if x != nil {
		return x.StudyId
	}
	return ""
}

func (x *RenderStudyExportRequest) GetExpectedContentRevision() int64 {
	if x != nil && x.ExpectedContentRevision != nil {
		return *x.ExpectedContentRevision
	}
	return 0
}

type ExportHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudyId       string                 `protobuf:"bytes,1,opt,name=study_id,json=studyId,proto3" json:"study_id,omitempty"`
	StudyRevision int64                  `protobuf:"varint,2,opt,name=study_revision,json=studyRevision,proto3" json:"study_revision,omitempty"`
	TotalBytes    int64                  `protobuf:"varint,3,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	FileCount     int32                  `protobuf:"varint,4,opt,name=file_count,json=fileCount,proto3" json:"file_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportHeader) Reset() {
	*x = ExportHeader{}
	mi := &file_wantstudy_v1_export_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportHeader) ProtoMessage() {}

func (x *ExportHeader) ProtoReflect() protoreflect.Message {
	mi := &file_wantstudy_v1_export_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportHeader.ProtoReflect.Descriptor instead.
func (*ExportHeader) Descriptor() ([]byte, []int) {
	return file_wantstudy_v1_export_proto_rawDescGZIP(), []int{1}
}

func (x *ExportHeader) GetStudyId() string {
	if x != nil {
		return x.StudyId
	}
	return ""
}

func (x *ExportHeader) GetStudyRevision() int64 {
	if x != nil {
		return x.StudyRevision
	}
	return 0
}

func (x *ExportHeader) GetTotalBytes() int64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *ExportHeader) GetFileCount() int32 {
	if x != nil {
		return x.FileCount
	}
	return 0
}

type ExportFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Sha256        string                 `protobuf:"bytes,3,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportFile) Reset() {
	*x = ExportFile{}
	mi := &file_wantstudy_v1_export_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportFile) ProtoMessage() {}

func (x *ExportFile) ProtoReflect() protoreflect.Message {
	mi := &file_wantstudy_v1_export_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportFile.ProtoReflect.Descriptor instead.
func (*ExportFile) Descriptor() ([]byte, []int) {
	return file_wantstudy_v1_export_proto_rawDescGZIP(), []int{2}
}

func (x *ExportFile) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ExportFile) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *ExportFile) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

type ExportChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*ExportChunk_Header
	//	*ExportChunk_File
	Value         isExportChunk_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportChunk) Reset() {
	*x = ExportChunk{}
	mi := &file_wantstudy_v1_export_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportChunk) ProtoMessage() {}

func (x *ExportChunk) ProtoReflect() protoreflect.Message {
	mi := &file_wantstudy_v1_export_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportChunk.ProtoReflect.Descriptor instead.
func (*ExportChunk) Descriptor() ([]byte, []int) {
	return file_wantstudy_v1_export_proto_rawDescGZIP(), []int{3}
}

func (x *ExportChunk) GetValue() isExportChunk_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ExportChunk) GetHeader() *ExportHeader {
	if x != nil {
		if x, ok := x.Value.(*ExportChunk_Header); ok {
			return x.Header
		}
	}
	return nil
}

func (x *ExportChunk) GetFile() *ExportFile {
	if x != nil {
		if x, ok := x.Value.(*ExportChunk_File); ok {
			return x.File
		}
	}
	return nil
}

type isExportChunk_Value interface {
	isExportChunk_Value()
}

type ExportChunk_Header struct {
	Header *ExportHeader `protobuf:"bytes,1,opt,name=header,proto3,oneof"`
}

type ExportChunk_File struct {
	File *ExportFile `protobuf:"bytes,2,opt,name=file,proto3,oneof"`
}

func (*ExportChunk_Header) isExportChunk_Value() {}

func (*ExportChunk_File) isExportChunk_Value() {}

var File_wantstudy_v1_export_proto protoreflect.FileDescriptor

const file_wantstudy_v1_export_proto_rawDesc = "" +
	"\n" +
	"\x19wantstudy/v1/export.proto\x12\fwantstudy.v1\"\x94\x01\n" +
	"\x18RenderStudyExportRequest\x12\x19\n" +
	"\bstudy_id\x18\x01 \x01(\tR\astudyId\x12?\n" +
	"\x19expected_content_revision\x18\x02 \x01(\x03H\x00R\x17expectedContentRevision\x88\x01\x01B\x1c\n" +
	"\x1a_expected_content_revision\"\x90\x01\n" +
	"\fExportHeader\x12\x19\n" +
	"\bstudy_id\x18\x01 \x01(\tR\astudyId\x12%\n" +
	"\x0estudy_revision\x18\x02 \x01(\x03R\rstudyRevision\x12\x1f\n" +
	"\vtotal_bytes\x18\x03 \x01(\x03R\n" +
	"totalBytes\x12\x1d\n" +
	"\n" +
	"file_count\x18\x04 \x01(\x05R\tfileCount\"R\n" +
	"\n" +
	"ExportFile\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\x12\x16\n" +
	"\x06sha256\x18\x03 \x01(\tR\x06sha256\"|\n" +
	"\vExportChunk\x124\n" +
	"\x06header\x18\x01 \x01(\v2\x1a.wantstudy.v1.ExportHeaderH\x00R\x06header\x12.\n" +
	"\x04file\x18\x02 \x01(\v2\x18.wantstudy.v1.ExportFileH\x00R\x04fileB\a\n" +
	"\x05value2i\n" +
	"\rExportService\x12X\n" +
	"\x11RenderStudyExport\x12&.wantstudy.v1.RenderStudyExportRequest\x1a\x19.wantstudy.v1.ExportChunk0\x01BSZQgithub.com/pchkauu/want-study/service/api/internal/proto/wantstudy/v1;wantstudyv1b\x06proto3"

var (
	file_wantstudy_v1_export_proto_rawDescOnce sync.Once
	file_wantstudy_v1_export_proto_rawDescData []byte
)

func file_wantstudy_v1_export_proto_rawDescGZIP() []byte {
	file_wantstudy_v1_export_proto_rawDescOnce.Do(func() {
		file_wantstudy_v1_export_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wantstudy_v1_export_proto_rawDesc), len(file_wantstudy_v1_export_proto_rawDesc)))
	})
	return file_wantstudy_v1_export_proto_rawDescData
}

var file_wantstudy_v1_export_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_wantstudy_v1_export_proto_goTypes = []any{
	(*RenderStudyExportRequest)(nil), // 0: wantstudy.v1.RenderStudyExportRequest
	(*ExportHeader)(nil),             // 1: wantstudy.v1.ExportHeader
	(*ExportFile)(nil),               // 2: wantstudy.v1.ExportFile
	(*ExportChunk)(nil),              // 3: wantstudy.v1.ExportChunk
}
var file_wantstudy_v1_export_proto_depIdxs = []int32{
	1, // 0: wantstudy.v1.ExportChunk.header:type_name -> wantstudy.v1.ExportHeader
	2, // 1: wantstudy.v1.ExportChunk.file:type_name -> wantstudy.v1.ExportFile
	0, // 2: wantstudy.v1.ExportService.RenderStudyExport:input_type -> wantstudy.v1.RenderStudyExportRequest
	3, // 3: wantstudy.v1.ExportService.RenderStudyExport:output_type -> wantstudy.v1.ExportChunk
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_wantstudy_v1_export_proto_init() }
func file_wantstudy_v1_export_proto_init() {
	if File_wantstudy_v1_export_proto != nil {
		return
	}
	file_wantstudy_v1_export_proto_msgTypes[0].OneofWrappers = []any{}
	file_wantstudy_v1_export_proto_msgTypes[3].OneofWrappers = []any{
		(*ExportChunk_Header)(nil),
		(*ExportChunk_File)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wantstudy_v1_export_proto_rawDesc), len(file_wantstudy_v1_export_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wantstudy_v1_export_proto_goTypes,
		DependencyIndexes: file_wantstudy_v1_export_proto_depIdxs,
		MessageInfos:      file_wantstudy_v1_export_proto_msgTypes,
	}.Build()
	File_wantstudy_v1_export_proto = out.File
	file_wantstudy_v1_export_proto_goTypes = nil
	file_wantstudy_v1_export_proto_depIdxs = nil
}
