// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: wantstudy/v1/knowledge.proto

package wantstudyv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KnowledgeService_CreateConcept_FullMethodName         = "/wantstudy.v1.KnowledgeService/CreateConcept"
	KnowledgeService_UpdateConcept_FullMethodName         = "/wantstudy.v1.KnowledgeService/UpdateConcept"
	KnowledgeService_ArchiveConcept_FullMethodName        = "/wantstudy.v1.KnowledgeService/ArchiveConcept"
	KnowledgeService_RestoreConcept_FullMethodName        = "/wantstudy.v1.KnowledgeService/RestoreConcept"
	KnowledgeService_AddConceptAlias_FullMethodName       = "/wantstudy.v1.KnowledgeService/AddConceptAlias"
	KnowledgeService_RemoveConceptAlias_FullMethodName    = "/wantstudy.v1.KnowledgeService/RemoveConceptAlias"
	KnowledgeService_LinkBlockConcept_FullMethodName      = "/wantstudy.v1.KnowledgeService/LinkBlockConcept"
	KnowledgeService_UnlinkBlockConcept_FullMethodName    = "/wantstudy.v1.KnowledgeService/UnlinkBlockConcept"
	KnowledgeService_PutConceptRelation_FullMethodName    = "/wantstudy.v1.KnowledgeService/PutConceptRelation"
	KnowledgeService_DeleteConceptRelation_FullMethodName = "/wantstudy.v1.KnowledgeService/DeleteConceptRelation"
	KnowledgeService_SearchConcepts_FullMethodName        = "/wantstudy.v1.KnowledgeService/SearchConcepts"
	KnowledgeService_GetConceptGraph_FullMethodName       = "/wantstudy.v1.KnowledgeService/GetConceptGraph"
)

// KnowledgeServiceClient is the client API for KnowledgeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KnowledgeServiceClient interface {
	CreateConcept(ctx context.Context, in *CreateConceptRequest, opts ...grpc.CallOption) (*Concept, error)
	UpdateConcept(ctx context.Context, in *UpdateConceptRequest, opts ...grpc.CallOption) (*Concept, error)
	ArchiveConcept(ctx context.Context, in *ChangeArchiveRequest, opts ...grpc.CallOption) (*Concept, error)
	RestoreConcept(ctx context.Context, in *ChangeArchiveRequest, opts ...grpc.CallOption) (*Concept, error)
	AddConceptAlias(ctx context.Context, in *ChangeConceptAliasRequest, opts ...grpc.CallOption) (*Concept, error)
	RemoveConceptAlias(ctx context.Context, in *ChangeConceptAliasRequest, opts ...grpc.CallOption) (*Concept, error)
	LinkBlockConcept(ctx context.Context, in *ChangeBlockConceptRequest, opts ...grpc.CallOption) (*Concept, error)
	UnlinkBlockConcept(ctx context.Context, in *ChangeBlockConceptRequest, opts ...grpc.CallOption) (*Concept, error)
	PutConceptRelation(ctx context.Context, in *PutConceptRelationRequest, opts ...grpc.CallOption) (*ConceptRelation, error)
	DeleteConceptRelation(ctx context.Context, in *DeleteConceptRelationRequest, opts ...grpc.CallOption) (*DeleteConceptRelationResponse, error)
	SearchConcepts(ctx context.Context, in *SearchConceptsRequest, opts ...grpc.CallOption) (*SearchConceptsResponse, error)
	GetConceptGraph(ctx context.Context, in *GetConceptGraphRequest, opts ...grpc.CallOption) (*ConceptGraph, error)
}

type knowledgeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKnowledgeServiceClient(cc grpc.ClientConnInterface) KnowledgeServiceClient {
	return &knowledgeServiceClient{cc}
}

func (c *knowledgeServiceClient) CreateConcept(ctx context.Context, in *CreateConceptRequest, opts ...grpc.CallOption) (*Concept, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Concept)
	err := c.cc.Invoke(ctx, KnowledgeService_CreateConcept_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeServiceClient) UpdateConcept(ctx context.Context, in *UpdateConceptRequest, opts ...grpc.CallOption) (*Concept, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Concept)
	err := c.cc.Invoke(ctx, KnowledgeService_UpdateConcept_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeServiceClient) ArchiveConcept(ctx context.Context, in *ChangeArchiveRequest, opts ...grpc.CallOption) (*Concept, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Concept)
	err := c.cc.Invoke(ctx, KnowledgeService_ArchiveConcept_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeServiceClient) RestoreConcept(ctx context.Context, in *ChangeArchiveRequest, opts ...grpc.CallOption) (*Concept, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Concept)
	err := c.cc.Invoke(ctx, KnowledgeService_RestoreConcept_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeServiceClient) AddConceptAlias(ctx context.Context, in *ChangeConceptAliasRequest, opts ...grpc.CallOption) (*Concept, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Concept)
	err := c.cc.Invoke(ctx, KnowledgeService_AddConceptAlias_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeServiceClient) RemoveConceptAlias(ctx context.Context, in *ChangeConceptAliasRequest, opts ...grpc.CallOption) (*Concept, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Concept)
	err := c.cc.Invoke(ctx, KnowledgeService_RemoveConceptAlias_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeServiceClient) LinkBlockConcept(ctx context.Context, in *ChangeBlockConceptRequest, opts ...grpc.CallOption) (*Concept, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Concept)
	err := c.cc.Invoke(ctx, KnowledgeService_LinkBlockConcept_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeServiceClient) UnlinkBlockConcept(ctx context.Context, in *ChangeBlockConceptRequest, opts ...grpc.CallOption) (*Concept, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Concept)
	err := c.cc.Invoke(ctx, KnowledgeService_UnlinkBlockConcept_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeServiceClient) PutConceptRelation(ctx context.Context, in *PutConceptRelationRequest, opts ...grpc.CallOption) (*ConceptRelation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConceptRelation)
	err := c.cc.Invoke(ctx, KnowledgeService_PutConceptRelation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeServiceClient) DeleteConceptRelation(ctx context.Context, in *DeleteConceptRelationRequest, opts ...grpc.CallOption) (*DeleteConceptRelationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteConceptRelationResponse)
	err := c.cc.Invoke(ctx, KnowledgeService_DeleteConceptRelation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeServiceClient) SearchConcepts(ctx context.Context, in *SearchConceptsRequest, opts ...grpc.CallOption) (*SearchConceptsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchConceptsResponse)
	err := c.cc.Invoke(ctx, KnowledgeService_SearchConcepts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeServiceClient) GetConceptGraph(ctx context.Context, in *GetConceptGraphRequest, opts ...grpc.CallOption) (*ConceptGraph, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConceptGraph)
	err := c.cc.Invoke(ctx, KnowledgeService_GetConceptGraph_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KnowledgeServiceServer is the server API for KnowledgeService service.
// All implementations must embed UnimplementedKnowledgeServiceServer
// for forward compatibility.
type KnowledgeServiceServer interface {
	CreateConcept(context.Context, *CreateConceptRequest) (*Concept, error)
	UpdateConcept(context.Context, *UpdateConceptRequest) (*Concept, error)
	ArchiveConcept(context.Context, *ChangeArchiveRequest) (*Concept, error)
	RestoreConcept(context.Context, *ChangeArchiveRequest) (*Concept, error)
	AddConceptAlias(context.Context, *ChangeConceptAliasRequest) (*Concept, error)
	RemoveConceptAlias(context.Context, *ChangeConceptAliasRequest) (*Concept, error)
	LinkBlockConcept(context.Context, *ChangeBlockConceptRequest) (*Concept, error)
	UnlinkBlockConcept(context.Context, *ChangeBlockConceptRequest) (*Concept, error)
	PutConceptRelation(context.Context, *PutConceptRelationRequest) (*ConceptRelation, error)
	DeleteConceptRelation(context.Context, *DeleteConceptRelationRequest) (*DeleteConceptRelationResponse, error)
	SearchConcepts(context.Context, *SearchConceptsRequest) (*SearchConceptsResponse, error)
	GetConceptGraph(context.Context, *GetConceptGraphRequest) (*ConceptGraph, error)
	mustEmbedUnimplementedKnowledgeServiceServer()
}

// UnimplementedKnowledgeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKnowledgeServiceServer struct{}

func (UnimplementedKnowledgeServiceServer) CreateConcept(context.Context, *CreateConceptRequest) (*Concept, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateConcept not implemented")
}
func (UnimplementedKnowledgeServiceServer) UpdateConcept(context.Context, *UpdateConceptRequest) (*Concept, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateConcept not implemented")
}
func (UnimplementedKnowledgeServiceServer) ArchiveConcept(context.Context, *ChangeArchiveRequest) (*Concept, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ArchiveConcept not implemented")
}
func (UnimplementedKnowledgeServiceServer) RestoreConcept(context.Context, *ChangeArchiveRequest) (*Concept, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RestoreConcept not implemented")
}
func (UnimplementedKnowledgeServiceServer) AddConceptAlias(context.Context, *ChangeConceptAliasRequest) (*Concept, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddConceptAlias not implemented")
}
func (UnimplementedKnowledgeServiceServer) RemoveConceptAlias(context.Context, *ChangeConceptAliasRequest) (*Concept, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveConceptAlias not implemented")
}
func (UnimplementedKnowledgeServiceServer) LinkBlockConcept(context.Context, *ChangeBlockConceptRequest) (*Concept, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LinkBlockConcept not implemented")
}
func (UnimplementedKnowledgeServiceServer) UnlinkBlockConcept(context.Context, *ChangeBlockConceptRequest) (*Concept, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnlinkBlockConcept not implemented")
}
func (UnimplementedKnowledgeServiceServer) PutConceptRelation(context.Context, *PutConceptRelationRequest) (*ConceptRelation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutConceptRelation not implemented")
}
func (UnimplementedKnowledgeServiceServer) DeleteConceptRelation(context.Context, *DeleteConceptRelationRequest) (*DeleteConceptRelationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteConceptRelation not implemented")
}
func (UnimplementedKnowledgeServiceServer) SearchConcepts(context.Context, *SearchConceptsRequest) (*SearchConceptsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchConcepts not implemented")
}
func (UnimplementedKnowledgeServiceServer) GetConceptGraph(context.Context, *GetConceptGraphRequest) (*ConceptGraph, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConceptGraph not implemented")
}
func (UnimplementedKnowledgeServiceServer) mustEmbedUnimplementedKnowledgeServiceServer() {}
func (UnimplementedKnowledgeServiceServer) testEmbeddedByValue()                          {}

// UnsafeKnowledgeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KnowledgeServiceServer will
// result in compilation errors.
type UnsafeKnowledgeServiceServer interface {
	mustEmbedUnimplementedKnowledgeServiceServer()
}

func RegisterKnowledgeServiceServer(s grpc.ServiceRegistrar, srv KnowledgeServiceServer) {
	// If the following call pancis, it indicates UnimplementedKnowledgeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KnowledgeService_ServiceDesc, srv)
}

func _KnowledgeService_CreateConcept_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateConceptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeServiceServer).CreateConcept(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeService_CreateConcept_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeServiceServer).CreateConcept(ctx, req.(*CreateConceptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeService_UpdateConcept_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateConceptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeServiceServer).UpdateConcept(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeService_UpdateConcept_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeServiceServer).UpdateConcept(ctx, req.(*UpdateConceptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeService_ArchiveConcept_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeArchiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeServiceServer).ArchiveConcept(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeService_ArchiveConcept_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeServiceServer).ArchiveConcept(ctx, req.(*ChangeArchiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeService_RestoreConcept_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeArchiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeServiceServer).RestoreConcept(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeService_RestoreConcept_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeServiceServer).RestoreConcept(ctx, req.(*ChangeArchiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeService_AddConceptAlias_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeConceptAliasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeServiceServer).AddConceptAlias(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeService_AddConceptAlias_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeServiceServer).AddConceptAlias(ctx, req.(*ChangeConceptAliasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeService_RemoveConceptAlias_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeConceptAliasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeServiceServer).RemoveConceptAlias(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeService_RemoveConceptAlias_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeServiceServer).RemoveConceptAlias(ctx, req.(*ChangeConceptAliasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeService_LinkBlockConcept_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeBlockConceptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeServiceServer).LinkBlockConcept(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeService_LinkBlockConcept_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeServiceServer).LinkBlockConcept(ctx, req.(*ChangeBlockConceptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeService_UnlinkBlockConcept_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeBlockConceptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeServiceServer).UnlinkBlockConcept(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeService_UnlinkBlockConcept_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeServiceServer).UnlinkBlockConcept(ctx, req.(*ChangeBlockConceptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeService_PutConceptRelation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutConceptRelationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeServiceServer).PutConceptRelation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeService_PutConceptRelation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeServiceServer).PutConceptRelation(ctx, req.(*PutConceptRelationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeService_DeleteConceptRelation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteConceptRelationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeServiceServer).DeleteConceptRelation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeService_DeleteConceptRelation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeServiceServer).DeleteConceptRelation(ctx, req.(*DeleteConceptRelationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeService_SearchConcepts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchConceptsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeServiceServer).SearchConcepts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeService_SearchConcepts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeServiceServer).SearchConcepts(ctx, req.(*SearchConceptsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeService_GetConceptGraph_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConceptGraphRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeServiceServer).GetConceptGraph(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeService_GetConceptGraph_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeServiceServer).GetConceptGraph(ctx, req.(*GetConceptGraphRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KnowledgeService_ServiceDesc is the grpc.ServiceDesc for KnowledgeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KnowledgeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wantstudy.v1.KnowledgeService",
	HandlerType: (*KnowledgeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateConcept",
			Handler:    _KnowledgeService_CreateConcept_Handler,
		},
		{
			MethodName: "UpdateConcept",
			Handler:    _KnowledgeService_UpdateConcept_Handler,
		},
		{
			MethodName: "ArchiveConcept",
			Handler:    _KnowledgeService_ArchiveConcept_Handler,
		},
		{
			MethodName: "RestoreConcept",
			Handler:    _KnowledgeService_RestoreConcept_Handler,
		},
		{
			MethodName: "AddConceptAlias",
			Handler:    _KnowledgeService_AddConceptAlias_Handler,
		},
		{
			MethodName: "RemoveConceptAlias",
			Handler:    _KnowledgeService_RemoveConceptAlias_Handler,
		},
		{
			MethodName: "LinkBlockConcept",
			Handler:    _KnowledgeService_LinkBlockConcept_Handler,
		},
		{
			MethodName: "UnlinkBlockConcept",
			Handler:    _KnowledgeService_UnlinkBlockConcept_Handler,
		},
		{
			MethodName: "PutConceptRelation",
			Handler:    _KnowledgeService_PutConceptRelation_Handler,
		},
		{
			MethodName: "DeleteConceptRelation",
			Handler:    _KnowledgeService_DeleteConceptRelation_Handler,
		},
		{
			MethodName: "SearchConcepts",
			Handler:    _KnowledgeService_SearchConcepts_Handler,
		},
		{
			MethodName: "GetConceptGraph",
			Handler:    _KnowledgeService_GetConceptGraph_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wantstudy/v1/knowledge.proto",
}
