// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: wantstudy/v1/knowledge.proto

package wantstudyv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConceptRelationType int32

const (
	ConceptRelationType_CONCEPT_RELATION_TYPE_UNSPECIFIED      ConceptRelationType = 0
	ConceptRelationType_CONCEPT_RELATION_TYPE_RELATED_TO       ConceptRelationType = 1
	ConceptRelationType_CONCEPT_RELATION_TYPE_PART_OF          ConceptRelationType = 2
	ConceptRelationType_CONCEPT_RELATION_TYPE_PREREQUISITE_FOR ConceptRelationType = 3
	ConceptRelationType_CONCEPT_RELATION_TYPE_CONTRASTS_WITH   ConceptRelationType = 4
	ConceptRelationType_CONCEPT_RELATION_TYPE_APPLIES_TO       ConceptRelationType = 5
)

// Enum value maps for ConceptRelationType.
var (
	ConceptRelationType_name = map[int32]string{
		0: "CONCEPT_RELATION_TYPE_UNSPECIFIED",
		1: "CONCEPT_RELATION_TYPE_RELATED_TO",
		2: "CONCEPT_RELATION_TYPE_PART_OF",
		3: "CONCEPT_RELATION_TYPE_PREREQUISITE_FOR",
		4: "CONCEPT_RELATION_TYPE_CONTRASTS_WITH",
		5: "CONCEPT_RELATION_TYPE_APPLIES_TO",
	}
	ConceptRelationType_value = map[string]int32{
		"CONCEPT_RELATION_TYPE_UNSPECIFIED":      0,
		"CONCEPT_RELATION_TYPE_RELATED_TO":       1,
		"CONCEPT_RELATION_TYPE_PART_OF":          2,
		"CONCEPT_RELATION_TYPE_PREREQUISITE_FOR": 3,
		"CONCEPT_RELATION_TYPE_CONTRASTS_WITH":   4,
		"CONCEPT_RELATION_TYPE_APPLIES_TO":       5,
	}
)

func (x ConceptRelationType) Enum() *ConceptRelationType {
	p := new(ConceptRelationType)
	*p = x
	return p
}

func (x ConceptRelationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConceptRelationType) Descriptor() protoreflect.EnumDescriptor {
	return file_wantstudy_v1_knowledge_proto_enumTypes[0].Descriptor()
}

func (ConceptRelationType) Type() protoreflect.EnumType {
	return &file_wantstudy_v1_knowledge_proto_enumTypes[0]
}

func (x ConceptRelationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConceptRelationType.Descriptor instead.
func (ConceptRelationType) EnumDescriptor() ([]byte, []int) {
	return file_wantstudy_v1_knowledge_proto_rawDescGZIP(), []int{0}
}

type Concept struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StudyId             string                 `protobuf:"bytes,2,opt,name=study_id,json=studyId,proto3" json:"study_id,omitempty"`
	Title               string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	DescriptionMarkdown string                 `protobuf:"bytes,4,opt,name=description_markdown,json=descriptionMarkdown,proto3" json:"description_markdown,omitempty"`
	ExportSlug          string                 `protobuf:"bytes,5,opt,name=export_slug,json=exportSlug,proto3" json:"export_slug,omitempty"`
	Aliases             []string               `protobuf:"bytes,6,rep,name=aliases,proto3" json:"aliases,omitempty"`
	BlockIds            []string               `protobuf:"bytes,7,rep,name=block_ids,json=blockIds,proto3" json:"block_ids,omitempty"`
	Version             int64                  `protobuf:"varint,8,opt,name=version,proto3" json:"version,omitempty"`
	Archived            bool                   `protobuf:"varint,9,opt,name=archived,proto3" json:"archived,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Concept) Reset() {
	*x = Concept{}
	mi := &file_wantstudy_v1_knowledge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Concept) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Concept) ProtoMessage() {}

func (x *Concept) ProtoReflect() protoreflect.Message {
	mi := &file_wantstudy_v1_knowledge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Concept.ProtoReflect.Descriptor instead.
func (*Concept) Descriptor() ([]byte, []int) {
	return file_wantstudy_v1_knowledge_proto_rawDescGZIP(), []int{0}
}

func (x *Concept) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Concept) GetStudyId() string {
	if x != nil {
		return x.StudyId
	}
	return ""
}

func (x *Concept) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Concept) GetDescriptionMarkdown() string {
	if x != nil {
		return x.DescriptionMarkdown
	}
	return ""
}

func (x *Concept) GetExportSlug() string {
	if x != nil {
		return x.ExportSlug
	}
	return ""
}

func (x *Concept) GetAliases() []string {
	if x != nil {
		return x.Aliases
	}
	return nil
}

func (x *Concept) GetBlockIds() []string {
	if x != nil {
		return x.BlockIds
	}
	return nil
}

func (x *Concept) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Concept) GetArchived() bool {
	if x != nil {
		return x.Archived
	}
	return false
}

type ConceptRelation struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StudyId         string                 `protobuf:"bytes,2,opt,name=study_id,json=studyId,proto3" json:"study_id,omitempty"`
	SourceConceptId string                 `protobuf:"bytes,3,opt,name=source_concept_id,json=sourceConceptId,proto3" json:"source_concept_id,omitempty"`
	TargetConceptId string                 `protobuf:"bytes,4,opt,name=target_concept_id,json=targetConceptId,proto3" json:"target_concept_id,omitempty"`
	Type            ConceptRelationType    `protobuf:"varint,5,opt,name=type,proto3,enum=wantstudy.v1.ConceptRelationType" json:"type,omitempty"`
	Version         int64                  `protobuf:"varint,6,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ConceptRelation) Reset() {
	*x = ConceptRelation{}
	mi := &file_wantstudy_v1_knowledge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConceptRelation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConceptRelation) ProtoMessage() {}

func (x *ConceptRelation) ProtoReflect() protoreflect.Message {
	mi := &file_wantstudy_v1_knowledge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConceptRelation.ProtoReflect.Descriptor instead.
func (*ConceptRelation) Descriptor() ([]byte, []int) {
	return file_wantstudy_v1_knowledge_proto_rawDescGZIP(), []int{1}
}

func (x *ConceptRelation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ConceptRelation) GetStudyId() string {
	if x != nil {
		return x.StudyId
	}
	return ""
}

func (x *ConceptRelation) GetSourceConceptId() string {
	if x != nil {
		return x.SourceConceptId
	}
	return ""
}

func (x *ConceptRelation) GetTargetConceptId() string {
	if x != nil {
		return x.TargetConceptId
	}
	return ""
}

func (x *ConceptRelation) GetType() ConceptRelationType {
	if x != nil {
		return x.Type
	}
	return ConceptRelationType_CONCEPT_RELATION_TYPE_UNSPECIFIED
}

func (x *ConceptRelation) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type CreateConceptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Concept       *Concept               `protobuf:"bytes,1,opt,name=concept,proto3" json:"concept,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateConceptRequest) Reset() {
	*x = CreateConceptRequest{}
	mi := &file_wantstudy_v1_knowledge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateConceptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateConceptRequest) ProtoMessage() {}

func (x *CreateConceptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wantstudy_v1_knowledge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateConceptRequest.ProtoReflect.Descriptor instead.
func (*CreateConceptRequest) Descriptor() ([]byte, []int) {
	return file_wantstudy_v1_knowledge_proto_rawDescGZIP(), []int{2}
}

func (x *CreateConceptRequest) GetConcept() *Concept {
	if x != nil {
		return x.Concept
	}
	return nil
}

type UpdateConceptRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Concept         *Concept               `protobuf:"bytes,1,opt,name=concept,proto3" json:"concept,omitempty"`
	ExpectedVersion int64                  `protobuf:"varint,2,opt,name=expected_version,json=expectedVersion,proto3" json:"expected_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateConceptRequest) Reset() {
	*x = UpdateConceptRequest{}
	mi := &file_wantstudy_v1_knowledge_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConceptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConceptRequest) ProtoMessage() {}

func (x *UpdateConceptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wantstudy_v1_knowledge_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConceptRequest.ProtoReflect.Descriptor instead.
func (*UpdateConceptRequest) Descriptor() ([]byte, []int) {
	return file_wantstudy_v1_knowledge_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateConceptRequest) GetConcept() *Concept {
	if x != nil {
		return x.Concept
	}
	return nil
}

func (x *UpdateConceptRequest) GetExpectedVersion() int64 {
	if x != nil {
		return x.ExpectedVersion
	}
	return 0
}

type ChangeConceptAliasRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ConceptId       string                 `protobuf:"bytes,1,opt,name=concept_id,json=conceptId,proto3" json:"concept_id,omitempty"`
	Alias           string                 `protobuf:"bytes,2,opt,name=alias,proto3" json:"alias,omitempty"`
	ExpectedVersion int64                  `protobuf:"varint,3,opt,name=expected_version,json=expectedVersion,proto3" json:"expected_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ChangeConceptAliasRequest) Reset() {
	*x = ChangeConceptAliasRequest{}
	mi := &file_wantstudy_v1_knowledge_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeConceptAliasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeConceptAliasRequest) ProtoMessage() {}

func (x *ChangeConceptAliasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wantstudy_v1_knowledge_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeConceptAliasRequest.ProtoReflect.Descriptor instead.
func (*ChangeConceptAliasRequest) Descriptor() ([]byte, []int) {
	return file_wantstudy_v1_knowledge_proto_rawDescGZIP(), []int{4}
}

func (x *ChangeConceptAliasRequest) GetConceptId() string {
	if x != nil {
		return x.ConceptId
	}
	return ""
}

func (x *ChangeConceptAliasRequest) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *ChangeConceptAliasRequest) GetExpectedVersion() int64 {
	if x != nil {
		return x.ExpectedVersion
	}
	return 0
}

type ChangeBlockConceptRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ConceptId       string                 `protobuf:"bytes,1,opt,name=concept_id,json=conceptId,proto3" json:"concept_id,omitempty"`
	BlockId         string                 `protobuf:"bytes,2,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	ExpectedVersion int64                  `protobuf:"varint,3,opt,name=expected_version,json=expectedVersion,proto3" json:"expected_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ChangeBlockConceptRequest) Reset() {
	*x = ChangeBlockConceptRequest{}
	mi := &file_wantstudy_v1_knowledge_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeBlockConceptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeBlockConceptRequest) ProtoMessage() {}

func (x *ChangeBlockConceptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wantstudy_v1_knowledge_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeBlockConceptRequest.ProtoReflect.Descriptor instead.
func (*ChangeBlockConceptRequest) Descriptor() ([]byte, []int) {
	return file_wantstudy_v1_knowledge_proto_rawDescGZIP(), []int{5}
}

func (x *ChangeBlockConceptRequest) GetConceptId() string {
	if x != nil {
		return x.ConceptId
	}
	return ""
}

func (x *ChangeBlockConceptRequest) GetBlockId() string {
	if x != nil {
		return x.BlockId
	}
	return ""
}

func (x *ChangeBlockConceptRequest) GetExpectedVersion() int64 {
	if x != nil {
		return x.ExpectedVersion
	}
	return 0
}

type PutConceptRelationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Relation      *ConceptRelation       `protobuf:"bytes,1,opt,name=relation,proto3" json:"relation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutConceptRelationRequest) Reset() {
	*x = PutConceptRelationRequest{}
	mi := &file_wantstudy_v1_knowledge_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutConceptRelationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutConceptRelationRequest) ProtoMessage() {}

func (x *PutConceptRelationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wantstudy_v1_knowledge_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutConceptRelationRequest.ProtoReflect.Descriptor instead.
func (*PutConceptRelationRequest) Descriptor() ([]byte, []int) {
	return file_wantstudy_v1_knowledge_proto_rawDescGZIP(), []int{6}
}

func (x *PutConceptRelationRequest) GetRelation() *ConceptRelation {
	if x != nil {
		return x.Relation
	}
	return nil
}

type DeleteConceptRelationRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ExpectedVersion int64                  `protobuf:"varint,2,opt,name=expected_version,json=expectedVersion,proto3" json:"expected_version,omitempty"`
	Confirmed       bool                   `protobuf:"varint,3,opt,name=confirmed,proto3" json:"confirmed,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DeleteConceptRelationRequest) Reset() {
	*x = DeleteConceptRelationRequest{}
	mi := &file_wantstudy_v1_knowledge_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteConceptRelationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteConceptRelationRequest) ProtoMessage() {}

func (x *DeleteConceptRelationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wantstudy_v1_knowledge_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteConceptRelationRequest.ProtoReflect.Descriptor instead.
func (*DeleteConceptRelationRequest) Descriptor() ([]byte, []int) {
	return file_wantstudy_v1_knowledge_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteConceptRelationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteConceptRelationRequest) GetExpectedVersion() int64 {
	if x != nil {
		return x.ExpectedVersion
	}
	return 0
}

func (x *DeleteConceptRelationRequest) GetConfirmed() bool {
	if x != nil {
		return x.Confirmed
	}
	return false
}

type DeleteConceptRelationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteConceptRelationResponse) Reset() {
	*x = DeleteConceptRelationResponse{}
	mi := &file_wantstudy_v1_knowledge_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteConceptRelationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteConceptRelationResponse) ProtoMessage() {}

func (x *DeleteConceptRelationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wantstudy_v1_knowledge_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteConceptRelationResponse.ProtoReflect.Descriptor instead.
func (*DeleteConceptRelationResponse) Descriptor() ([]byte, []int) {
	return file_wantstudy_v1_knowledge_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteConceptRelationResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type SearchConceptsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	StudyId         string                 `protobuf:"bytes,1,opt,name=study_id,json=studyId,proto3" json:"study_id,omitempty"`
	Query           string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	IncludeArchived bool                   `protobuf:"varint,3,opt,name=include_archived,json=includeArchived,proto3" json:"include_archived,omitempty"`
	Limit           int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SearchConceptsRequest) Reset() {
	*x = SearchConceptsRequest{}
	mi := &file_wantstudy_v1_knowledge_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchConceptsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchConceptsRequest) ProtoMessage() {}

func (x *SearchConceptsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wantstudy_v1_knowledge_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchConceptsRequest.ProtoReflect.Descriptor instead.
func (*SearchConceptsRequest) Descriptor() ([]byte, []int) {
	return file_wantstudy_v1_knowledge_proto_rawDescGZIP(), []int{9}
}

func (x *SearchConceptsRequest) GetStudyId() string {
	if x != nil {
		return x.StudyId
	}
	return ""
}

func (x *SearchConceptsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchConceptsRequest) GetIncludeArchived() bool {
	if x != nil {
		return x.IncludeArchived
	}
	return false
}

func (x *SearchConceptsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SearchConceptsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Concepts      []*Concept             `protobuf:"bytes,1,rep,name=concepts,proto3" json:"concepts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchConceptsResponse) Reset() {
	*x = SearchConceptsResponse{}
	mi := &file_wantstudy_v1_knowledge_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchConceptsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchConceptsResponse) ProtoMessage() {}

func (x *SearchConceptsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wantstudy_v1_knowledge_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchConceptsResponse.ProtoReflect.Descriptor instead.
func (*SearchConceptsResponse) Descriptor() ([]byte, []int) {
	return file_wantstudy_v1_knowledge_proto_rawDescGZIP(), []int{10}
}

func (x *SearchConceptsResponse) GetConcepts() []*Concept {
	if x != nil {
		return x.Concepts
	}
	return nil
}

type GetConceptGraphRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	StudyId           string                 `protobuf:"bytes,1,opt,name=study_id,json=studyId,proto3" json:"study_id,omitempty"`
	SelectedConceptId *string                `protobuf:"bytes,2,opt,name=selected_concept_id,json=selectedConceptId,proto3,oneof" json:"selected_concept_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetConceptGraphRequest) Reset() {
	*x = GetConceptGraphRequest{}
	mi := &file_wantstudy_v1_knowledge_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConceptGraphRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConceptGraphRequest) ProtoMessage() {}

func (x *GetConceptGraphRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wantstudy_v1_knowledge_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConceptGraphRequest.ProtoReflect.Descriptor instead.
func (*GetConceptGraphRequest) Descriptor() ([]byte, []int) {
	return file_wantstudy_v1_knowledge_proto_rawDescGZIP(), []int{11}
}

func (x *GetConceptGraphRequest) GetStudyId() string {
	if x != nil {
		return x.StudyId
	}
	return ""
}

func (x *GetConceptGraphRequest) GetSelectedConceptId() string {
	if x != nil && x.SelectedConceptId != nil {
		return *x.SelectedConceptId
	}
	return ""
}

type ConceptGraph struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Concepts      []*Concept             `protobuf:"bytes,1,rep,name=concepts,proto3" json:"concepts,omitempty"`
	Relations     []*ConceptRelation     `protobuf:"bytes,2,rep,name=relations,proto3" json:"relations,omitempty"`
	Truncated     bool                   `protobuf:"varint,3,opt,name=truncated,proto3" json:"truncated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConceptGraph) Reset() {
	*x = ConceptGraph{}
	mi := &file_wantstudy_v1_knowledge_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConceptGraph) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConceptGraph) ProtoMessage() {}

func (x *ConceptGraph) ProtoReflect() protoreflect.Message {
	mi := &file_wantstudy_v1_knowledge_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConceptGraph.ProtoReflect.Descriptor instead.
func (*ConceptGraph) Descriptor() ([]byte, []int) {
	return file_wantstudy_v1_knowledge_proto_rawDescGZIP(), []int{12}
}

func (x *ConceptGraph) GetConcepts() []*Concept {
	if x != nil {
		return x.Concepts
	}
	return nil
}

func (x *ConceptGraph) GetRelations() []*ConceptRelation {
	if x != nil {
		return x.Relations
	}
	return nil
}

func (x *ConceptGraph) GetTruncated() bool {
	if x != nil {
		return x.Truncated
	}
	return false
}

var File_wantstudy_v1_knowledge_proto protoreflect.FileDescriptor

const file_wantstudy_v1_knowledge_proto_rawDesc = "" +
	"\n" +
	"\x1cwantstudy/v1/knowledge.proto\x12\fwantstudy.v1\x1a\x18wantstudy/v1/study.proto\"\x8b\x02\n" +
	"\aConcept\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bstudy_id\x18\x02 \x01(\tR\astudyId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x121\n" +
	"\x14description_markdown\x18\x04 \x01(\tR\x13descriptionMarkdown\x12\x1f\n" +
	"\vexport_slug\x18\x05 \x01(\tR\n" +
	"exportSlug\x12\x18\n" +
	"\aaliases\x18\x06 \x03(\tR\aaliases\x12\x1b\n" +
	"\tblock_ids\x18\a \x03(\tR\bblockIds\x12\x18\n" +
	"\aversion\x18\b \x01(\x03R\aversion\x12\x1a\n" +
	"\barchived\x18\t \x01(\bR\barchived\"\xe5\x01\n" +
	"\x0fConceptRelation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bstudy_id\x18\x02 \x01(\tR\astudyId\x12*\n" +
	"\x11source_concept_id\x18\x03 \x01(\tR\x0fsourceConceptId\x12*\n" +
	"\x11target_concept_id\x18\x04 \x01(\tR\x0ftargetConceptId\x125\n" +
	"\x04type\x18\x05 \x01(\x0e2!.wantstudy.v1.ConceptRelationTypeR\x04type\x12\x18\n" +
	"\aversion\x18\x06 \x01(\x03R\aversion\"G\n" +
	"\x14CreateConceptRequest\x12/\n" +
	"\aconcept\x18\x01 \x01(\v2\x15.wantstudy.v1.ConceptR\aconcept\"r\n" +
	"\x14UpdateConceptRequest\x12/\n" +
	"\aconcept\x18\x01 \x01(\v2\x15.wantstudy.v1.ConceptR\aconcept\x12)\n" +
	"\x10expected_version\x18\x02 \x01(\x03R\x0fexpectedVersion\"{\n" +
	"\x19ChangeConceptAliasRequest\x12\x1d\n" +
	"\n" +
	"concept_id\x18\x01 \x01(\tR\tconceptId\x12\x14\n" +
	"\x05alias\x18\x02 \x01(\tR\x05alias\x12)\n" +
	"\x10expected_version\x18\x03 \x01(\x03R\x0fexpectedVersion\"\x80\x01\n" +
	"\x19ChangeBlockConceptRequest\x12\x1d\n" +
	"\n" +
	"concept_id\x18\x01 \x01(\tR\tconceptId\x12\x19\n" +
	"\bblock_id\x18\x02 \x01(\tR\ablockId\x12)\n" +
	"\x10expected_version\x18\x03 \x01(\x03R\x0fexpectedVersion\"V\n" +
	"\x19PutConceptRelationRequest\x129\n" +
	"\brelation\x18\x01 \x01(\v2\x1d.wantstudy.v1.ConceptRelationR\brelation\"w\n" +
	"\x1cDeleteConceptRelationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12)\n" +
	"\x10expected_version\x18\x02 \x01(\x03R\x0fexpectedVersion\x12\x1c\n" +
	"\tconfirmed\x18\x03 \x01(\bR\tconfirmed\"/\n" +
	"\x1dDeleteConceptRelationResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x89\x01\n" +
	"\x15SearchConceptsRequest\x12\x19\n" +
	"\bstudy_id\x18\x01 \x01(\tR\astudyId\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12)\n" +
	"\x10include_archived\x18\x03 \x01(\bR\x0fincludeArchived\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"K\n" +
	"\x16SearchConceptsResponse\x121\n" +
	"\bconcepts\x18\x01 \x03(\v2\x15.wantstudy.v1.ConceptR\bconcepts\"\x80\x01\n" +
	"\x16GetConceptGraphRequest\x12\x19\n" +
	"\bstudy_id\x18\x01 \x01(\tR\astudyId\x123\n" +
	"\x13selected_concept_id\x18\x02 \x01(\tH\x00R\x11selectedConceptId\x88\x01\x01B\x16\n" +
	"\x14_selected_concept_id\"\x9c\x01\n" +
	"\fConceptGraph\x121\n" +
	"\bconcepts\x18\x01 \x03(\v2\x15.wantstudy.v1.ConceptR\bconcepts\x12;\n" +
	"\trelations\x18\x02 \x03(\v2\x1d.wantstudy.v1.ConceptRelationR\trelations\x12\x1c\n" +
	"\ttruncated\x18\x03 \x01(\bR\ttruncated*\x81\x02\n" +
	"\x13ConceptRelationType\x12%\n" +
	"!CONCEPT_RELATION_TYPE_UNSPECIFIED\x10\x00\x12$\n" +
	" CONCEPT_RELATION_TYPE_RELATED_TO\x10\x01\x12!\n" +
	"\x1dCONCEPT_RELATION_TYPE_PART_OF\x10\x02\x12*\n" +
	"&CONCEPT_RELATION_TYPE_PREREQUISITE_FOR\x10\x03\x12(\n" +
	"$CONCEPT_RELATION_TYPE_CONTRASTS_WITH\x10\x04\x12$\n" +
	" CONCEPT_RELATION_TYPE_APPLIES_TO\x10\x052\x99\b\n" +
	"\x10KnowledgeService\x12J\n" +
	"\rCreateConcept\x12\".wantstudy.v1.CreateConceptRequest\x1a\x15.wantstudy.v1.Concept\x12J\n" +
	"\rUpdateConcept\x12\".wantstudy.v1.UpdateConceptRequest\x1a\x15.wantstudy.v1.Concept\x12K\n" +
	"\x0eArchiveConcept\x12\".wantstudy.v1.ChangeArchiveRequest\x1a\x15.wantstudy.v1.Concept\x12K\n" +
	"\x0eRestoreConcept\x12\".wantstudy.v1.ChangeArchiveRequest\x1a\x15.wantstudy.v1.Concept\x12Q\n" +
	"\x0fAddConceptAlias\x12'.wantstudy.v1.ChangeConceptAliasRequest\x1a\x15.wantstudy.v1.Concept\x12T\n" +
	"\x12RemoveConceptAlias\x12'.wantstudy.v1.ChangeConceptAliasRequest\x1a\x15.wantstudy.v1.Concept\x12R\n" +
	"\x10LinkBlockConcept\x12'.wantstudy.v1.ChangeBlockConceptRequest\x1a\x15.wantstudy.v1.Concept\x12T\n" +
	"\x12UnlinkBlockConcept\x12'.wantstudy.v1.ChangeBlockConceptRequest\x1a\x15.wantstudy.v1.Concept\x12\\\n" +
	"\x12PutConceptRelation\x12'.wantstudy.v1.PutConceptRelationRequest\x1a\x1d.wantstudy.v1.ConceptRelation\x12p\n" +
	"\x15DeleteConceptRelation\x12*.wantstudy.v1.DeleteConceptRelationRequest\x1a+.wantstudy.v1.DeleteConceptRelationResponse\x12[\n" +
	"\x0eSearchConcepts\x12#.wantstudy.v1.SearchConceptsRequest\x1a$.wantstudy.v1.SearchConceptsResponse\x12S\n" +
	"\x0fGetConceptGraph\x12$.wantstudy.v1.GetConceptGraphRequest\x1a\x1a.wantstudy.v1.ConceptGraphBSZQgithub.com/pchkauu/want-study/service/api/internal/proto/wantstudy/v1;wantstudyv1b\x06proto3"

var (
	file_wantstudy_v1_knowledge_proto_rawDescOnce sync.Once
	file_wantstudy_v1_knowledge_proto_rawDescData []byte
)

func file_wantstudy_v1_knowledge_proto_rawDescGZIP() []byte {
	file_wantstudy_v1_knowledge_proto_rawDescOnce.Do(func() {
		file_wantstudy_v1_knowledge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wantstudy_v1_knowledge_proto_rawDesc), len(file_wantstudy_v1_knowledge_proto_rawDesc)))
	})
	return file_wantstudy_v1_knowledge_proto_rawDescData
}

var file_wantstudy_v1_knowledge_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_wantstudy_v1_knowledge_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_wantstudy_v1_knowledge_proto_goTypes = []any{
	(ConceptRelationType)(0),              // 0: wantstudy.v1.ConceptRelationType
	(*Concept)(nil),                       // 1: wantstudy.v1.Concept
	(*ConceptRelation)(nil),               // 2: wantstudy.v1.ConceptRelation
	(*CreateConceptRequest)(nil),          // 3: wantstudy.v1.CreateConceptRequest
	(*UpdateConceptRequest)(nil),          // 4: wantstudy.v1.UpdateConceptRequest
	(*ChangeConceptAliasRequest)(nil),     // 5: wantstudy.v1.ChangeConceptAliasRequest
	(*ChangeBlockConceptRequest)(nil),     // 6: wantstudy.v1.ChangeBlockConceptRequest
	(*PutConceptRelationRequest)(nil),     // 7: wantstudy.v1.PutConceptRelationRequest
	(*DeleteConceptRelationRequest)(nil),  // 8: wantstudy.v1.DeleteConceptRelationRequest
	(*DeleteConceptRelationResponse)(nil), // 9: wantstudy.v1.DeleteConceptRelationResponse
	(*SearchConceptsRequest)(nil),         // 10: wantstudy.v1.SearchConceptsRequest
	(*SearchConceptsResponse)(nil),        // 11: wantstudy.v1.SearchConceptsResponse
	(*GetConceptGraphRequest)(nil),        // 12: wantstudy.v1.GetConceptGraphRequest
	(*ConceptGraph)(nil),                  // 13: wantstudy.v1.ConceptGraph
	(*ChangeArchiveRequest)(nil),          // 14: wantstudy.v1.ChangeArchiveRequest
}
var file_wantstudy_v1_knowledge_proto_depIdxs = []int32{
	0,  // 0: wantstudy.v1.ConceptRelation.type:type_name -> wantstudy.v1.ConceptRelationType
	1,  // 1: wantstudy.v1.CreateConceptRequest.concept:type_name -> wantstudy.v1.Concept
	1,  // 2: wantstudy.v1.UpdateConceptRequest.concept:type_name -> wantstudy.v1.Concept
	2,  // 3: wantstudy.v1.PutConceptRelationRequest.relation:type_name -> wantstudy.v1.ConceptRelation
	1,  // 4: wantstudy.v1.SearchConceptsResponse.concepts:type_name -> wantstudy.v1.Concept
	1,  // 5: wantstudy.v1.ConceptGraph.concepts:type_name -> wantstudy.v1.Concept
	2,  // 6: wantstudy.v1.ConceptGraph.relations:type_name -> wantstudy.v1.ConceptRelation
	3,  // 7: wantstudy.v1.KnowledgeService.CreateConcept:input_type -> wantstudy.v1.CreateConceptRequest
	4,  // 8: wantstudy.v1.KnowledgeService.UpdateConcept:input_type -> wantstudy.v1.UpdateConceptRequest
	14, // 9: wantstudy.v1.KnowledgeService.ArchiveConcept:input_type -> wantstudy.v1.ChangeArchiveRequest
	14, // 10: wantstudy.v1.KnowledgeService.RestoreConcept:input_type -> wantstudy.v1.ChangeArchiveRequest
	5,  // 11: wantstudy.v1.KnowledgeService.AddConceptAlias:input_type -> wantstudy.v1.ChangeConceptAliasRequest
	5,  // 12: wantstudy.v1.KnowledgeService.RemoveConceptAlias:input_type -> wantstudy.v1.ChangeConceptAliasRequest
	6,  // 13: wantstudy.v1.KnowledgeService.LinkBlockConcept:input_type -> wantstudy.v1.ChangeBlockConceptRequest
	6,  // 14: wantstudy.v1.KnowledgeService.UnlinkBlockConcept:input_type -> wantstudy.v1.ChangeBlockConceptRequest
	7,  // 15: wantstudy.v1.KnowledgeService.PutConceptRelation:input_type -> wantstudy.v1.PutConceptRelationRequest
	8,  // 16: wantstudy.v1.KnowledgeService.DeleteConceptRelation:input_type -> wantstudy.v1.DeleteConceptRelationRequest
	10, // 17: wantstudy.v1.KnowledgeService.SearchConcepts:input_type -> wantstudy.v1.SearchConceptsRequest
	12, // 18: wantstudy.v1.KnowledgeService.GetConceptGraph:input_type -> wantstudy.v1.GetConceptGraphRequest
	1,  // 19: wantstudy.v1.KnowledgeService.CreateConcept:output_type -> wantstudy.v1.Concept
	1,  // 20: wantstudy.v1.KnowledgeService.UpdateConcept:output_type -> wantstudy.v1.Concept
	1,  // 21: wantstudy.v1.KnowledgeService.ArchiveConcept:output_type -> wantstudy.v1.Concept
	1,  // 22: wantstudy.v1.KnowledgeService.RestoreConcept:output_type -> wantstudy.v1.Concept
	1,  // 23: wantstudy.v1.KnowledgeService.AddConceptAlias:output_type -> wantstudy.v1.Concept
	1,  // 24: wantstudy.v1.KnowledgeService.RemoveConceptAlias:output_type -> wantstudy.v1.Concept
	1,  // 25: wantstudy.v1.KnowledgeService.LinkBlockConcept:output_type -> wantstudy.v1.Concept
	1,  // 26: wantstudy.v1.KnowledgeService.UnlinkBlockConcept:output_type -> wantstudy.v1.Concept
	2,  // 27: wantstudy.v1.KnowledgeService.PutConceptRelation:output_type -> wantstudy.v1.ConceptRelation
	9,  // 28: wantstudy.v1.KnowledgeService.DeleteConceptRelation:output_type -> wantstudy.v1.DeleteConceptRelationResponse
	11, // 29: wantstudy.v1.KnowledgeService.SearchConcepts:output_type -> wantstudy.v1.SearchConceptsResponse
	13, // 30: wantstudy.v1.KnowledgeService.GetConceptGraph:output_type -> wantstudy.v1.ConceptGraph
	19, // [19:31] is the sub-list for method output_type
	7,  // [7:19] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_wantstudy_v1_knowledge_proto_init() }
func file_wantstudy_v1_knowledge_proto_init() {
	if File_wantstudy_v1_knowledge_proto != nil {
		return
	}
	file_wantstudy_v1_study_proto_init()
	file_wantstudy_v1_knowledge_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wantstudy_v1_knowledge_proto_rawDesc), len(file_wantstudy_v1_knowledge_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wantstudy_v1_knowledge_proto_goTypes,
		DependencyIndexes: file_wantstudy_v1_knowledge_proto_depIdxs,
		EnumInfos:         file_wantstudy_v1_knowledge_proto_enumTypes,
		MessageInfos:      file_wantstudy_v1_knowledge_proto_msgTypes,
	}.Build()
	File_wantstudy_v1_knowledge_proto = out.File
	file_wantstudy_v1_knowledge_proto_goTypes = nil
	file_wantstudy_v1_knowledge_proto_depIdxs = nil
}
