// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: wantstudy/v1/lesson_content.proto

package wantstudyv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LessonContentService_GetLessonWorkspace_FullMethodName   = "/wantstudy.v1.LessonContentService/GetLessonWorkspace"
	LessonContentService_CreateNoteBlock_FullMethodName      = "/wantstudy.v1.LessonContentService/CreateNoteBlock"
	LessonContentService_UpdateNoteBlock_FullMethodName      = "/wantstudy.v1.LessonContentService/UpdateNoteBlock"
	LessonContentService_DeleteNoteBlock_FullMethodName      = "/wantstudy.v1.LessonContentService/DeleteNoteBlock"
	LessonContentService_CreateHomeworkTask_FullMethodName   = "/wantstudy.v1.LessonContentService/CreateHomeworkTask"
	LessonContentService_UpdateHomeworkTask_FullMethodName   = "/wantstudy.v1.LessonContentService/UpdateHomeworkTask"
	LessonContentService_DeleteHomeworkTask_FullMethodName   = "/wantstudy.v1.LessonContentService/DeleteHomeworkTask"
	LessonContentService_CreateCodeFile_FullMethodName       = "/wantstudy.v1.LessonContentService/CreateCodeFile"
	LessonContentService_UpdateCodeFile_FullMethodName       = "/wantstudy.v1.LessonContentService/UpdateCodeFile"
	LessonContentService_DeleteCodeFile_FullMethodName       = "/wantstudy.v1.LessonContentService/DeleteCodeFile"
	LessonContentService_ReorderLessonContent_FullMethodName = "/wantstudy.v1.LessonContentService/ReorderLessonContent"
)

// LessonContentServiceClient is the client API for LessonContentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LessonContentServiceClient interface {
	GetLessonWorkspace(ctx context.Context, in *GetLessonWorkspaceRequest, opts ...grpc.CallOption) (*LessonWorkspace, error)
	CreateNoteBlock(ctx context.Context, in *CreateNoteBlockRequest, opts ...grpc.CallOption) (*NoteBlock, error)
	UpdateNoteBlock(ctx context.Context, in *UpdateNoteBlockRequest, opts ...grpc.CallOption) (*NoteBlock, error)
	DeleteNoteBlock(ctx context.Context, in *DeleteContentRequest, opts ...grpc.CallOption) (*DeleteContentResponse, error)
	CreateHomeworkTask(ctx context.Context, in *CreateHomeworkTaskRequest, opts ...grpc.CallOption) (*HomeworkTask, error)
	UpdateHomeworkTask(ctx context.Context, in *UpdateHomeworkTaskRequest, opts ...grpc.CallOption) (*HomeworkTask, error)
	DeleteHomeworkTask(ctx context.Context, in *DeleteContentRequest, opts ...grpc.CallOption) (*DeleteContentResponse, error)
	CreateCodeFile(ctx context.Context, in *CreateCodeFileRequest, opts ...grpc.CallOption) (*CodeFile, error)
	UpdateCodeFile(ctx context.Context, in *UpdateCodeFileRequest, opts ...grpc.CallOption) (*CodeFile, error)
	DeleteCodeFile(ctx context.Context, in *DeleteContentRequest, opts ...grpc.CallOption) (*DeleteContentResponse, error)
	ReorderLessonContent(ctx context.Context, in *ReorderLessonContentRequest, opts ...grpc.CallOption) (*LessonWorkspace, error)
}

type lessonContentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLessonContentServiceClient(cc grpc.ClientConnInterface) LessonContentServiceClient {
	return &lessonContentServiceClient{cc}
}

func (c *lessonContentServiceClient) GetLessonWorkspace(ctx context.Context, in *GetLessonWorkspaceRequest, opts ...grpc.CallOption) (*LessonWorkspace, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LessonWorkspace)
	err := c.cc.Invoke(ctx, LessonContentService_GetLessonWorkspace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lessonContentServiceClient) CreateNoteBlock(ctx context.Context, in *CreateNoteBlockRequest, opts ...grpc.CallOption) (*NoteBlock, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NoteBlock)
	err := c.cc.Invoke(ctx, LessonContentService_CreateNoteBlock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lessonContentServiceClient) UpdateNoteBlock(ctx context.Context, in *UpdateNoteBlockRequest, opts ...grpc.CallOption) (*NoteBlock, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NoteBlock)
	err := c.cc.Invoke(ctx, LessonContentService_UpdateNoteBlock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lessonContentServiceClient) DeleteNoteBlock(ctx context.Context, in *DeleteContentRequest, opts ...grpc.CallOption) (*DeleteContentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteContentResponse)
	err := c.cc.Invoke(ctx, LessonContentService_DeleteNoteBlock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lessonContentServiceClient) CreateHomeworkTask(ctx context.Context, in *CreateHomeworkTaskRequest, opts ...grpc.CallOption) (*HomeworkTask, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HomeworkTask)
	err := c.cc.Invoke(ctx, LessonContentService_CreateHomeworkTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lessonContentServiceClient) UpdateHomeworkTask(ctx context.Context, in *UpdateHomeworkTaskRequest, opts ...grpc.CallOption) (*HomeworkTask, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HomeworkTask)
	err := c.cc.Invoke(ctx, LessonContentService_UpdateHomeworkTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lessonContentServiceClient) DeleteHomeworkTask(ctx context.Context, in *DeleteContentRequest, opts ...grpc.CallOption) (*DeleteContentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteContentResponse)
	err := c.cc.Invoke(ctx, LessonContentService_DeleteHomeworkTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lessonContentServiceClient) CreateCodeFile(ctx context.Context, in *CreateCodeFileRequest, opts ...grpc.CallOption) (*CodeFile, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CodeFile)
	err := c.cc.Invoke(ctx, LessonContentService_CreateCodeFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lessonContentServiceClient) UpdateCodeFile(ctx context.Context, in *UpdateCodeFileRequest, opts ...grpc.CallOption) (*CodeFile, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CodeFile)
	err := c.cc.Invoke(ctx, LessonContentService_UpdateCodeFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lessonContentServiceClient) DeleteCodeFile(ctx context.Context, in *DeleteContentRequest, opts ...grpc.CallOption) (*DeleteContentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteContentResponse)
	err := c.cc.Invoke(ctx, LessonContentService_DeleteCodeFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lessonContentServiceClient) ReorderLessonContent(ctx context.Context, in *ReorderLessonContentRequest, opts ...grpc.CallOption) (*LessonWorkspace, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LessonWorkspace)
	err := c.cc.Invoke(ctx, LessonContentService_ReorderLessonContent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LessonContentServiceServer is the server API for LessonContentService service.
// All implementations must embed UnimplementedLessonContentServiceServer
// for forward compatibility.
type LessonContentServiceServer interface {
	GetLessonWorkspace(context.Context, *GetLessonWorkspaceRequest) (*LessonWorkspace, error)
	CreateNoteBlock(context.Context, *CreateNoteBlockRequest) (*NoteBlock, error)
	UpdateNoteBlock(context.Context, *UpdateNoteBlockRequest) (*NoteBlock, error)
	DeleteNoteBlock(context.Context, *DeleteContentRequest) (*DeleteContentResponse, error)
	CreateHomeworkTask(context.Context, *CreateHomeworkTaskRequest) (*HomeworkTask, error)
	UpdateHomeworkTask(context.Context, *UpdateHomeworkTaskRequest) (*HomeworkTask, error)
	DeleteHomeworkTask(context.Context, *DeleteContentRequest) (*DeleteContentResponse, error)
	CreateCodeFile(context.Context, *CreateCodeFileRequest) (*CodeFile, error)
	UpdateCodeFile(context.Context, *UpdateCodeFileRequest) (*CodeFile, error)
	DeleteCodeFile(context.Context, *DeleteContentRequest) (*DeleteContentResponse, error)
	ReorderLessonContent(context.Context, *ReorderLessonContentRequest) (*LessonWorkspace, error)
	mustEmbedUnimplementedLessonContentServiceServer()
}

// UnimplementedLessonContentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLessonContentServiceServer struct{}

func (UnimplementedLessonContentServiceServer) GetLessonWorkspace(context.Context, *GetLessonWorkspaceRequest) (*LessonWorkspace, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLessonWorkspace not implemented")
}
func (UnimplementedLessonContentServiceServer) CreateNoteBlock(context.Context, *CreateNoteBlockRequest) (*NoteBlock, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateNoteBlock not implemented")
}
func (UnimplementedLessonContentServiceServer) UpdateNoteBlock(context.Context, *UpdateNoteBlockRequest) (*NoteBlock, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateNoteBlock not implemented")
}
func (UnimplementedLessonContentServiceServer) DeleteNoteBlock(context.Context, *DeleteContentRequest) (*DeleteContentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteNoteBlock not implemented")
}
func (UnimplementedLessonContentServiceServer) CreateHomeworkTask(context.Context, *CreateHomeworkTaskRequest) (*HomeworkTask, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateHomeworkTask not implemented")
}
func (UnimplementedLessonContentServiceServer) UpdateHomeworkTask(context.Context, *UpdateHomeworkTaskRequest) (*HomeworkTask, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateHomeworkTask not implemented")
}
func (UnimplementedLessonContentServiceServer) DeleteHomeworkTask(context.Context, *DeleteContentRequest) (*DeleteContentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteHomeworkTask not implemented")
}
func (UnimplementedLessonContentServiceServer) CreateCodeFile(context.Context, *CreateCodeFileRequest) (*CodeFile, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCodeFile not implemented")
}
func (UnimplementedLessonContentServiceServer) UpdateCodeFile(context.Context, *UpdateCodeFileRequest) (*CodeFile, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCodeFile not implemented")
}
func (UnimplementedLessonContentServiceServer) DeleteCodeFile(context.Context, *DeleteContentRequest) (*DeleteContentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCodeFile not implemented")
}
func (UnimplementedLessonContentServiceServer) ReorderLessonContent(context.Context, *ReorderLessonContentRequest) (*LessonWorkspace, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReorderLessonContent not implemented")
}
func (UnimplementedLessonContentServiceServer) mustEmbedUnimplementedLessonContentServiceServer() {}
func (UnimplementedLessonContentServiceServer) testEmbeddedByValue()                              {}

// UnsafeLessonContentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LessonContentServiceServer will
// result in compilation errors.
type UnsafeLessonContentServiceServer interface {
	mustEmbedUnimplementedLessonContentServiceServer()
}

func RegisterLessonContentServiceServer(s grpc.ServiceRegistrar, srv LessonContentServiceServer) {
	// If the following call pancis, it indicates UnimplementedLessonContentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LessonContentService_ServiceDesc, srv)
}

func _LessonContentService_GetLessonWorkspace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLessonWorkspaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LessonContentServiceServer).GetLessonWorkspace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LessonContentService_GetLessonWorkspace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LessonContentServiceServer).GetLessonWorkspace(ctx, req.(*GetLessonWorkspaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LessonContentService_CreateNoteBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNoteBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LessonContentServiceServer).CreateNoteBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LessonContentService_CreateNoteBlock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LessonContentServiceServer).CreateNoteBlock(ctx, req.(*CreateNoteBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LessonContentService_UpdateNoteBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateNoteBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LessonContentServiceServer).UpdateNoteBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LessonContentService_UpdateNoteBlock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LessonContentServiceServer).UpdateNoteBlock(ctx, req.(*UpdateNoteBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LessonContentService_DeleteNoteBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LessonContentServiceServer).DeleteNoteBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LessonContentService_DeleteNoteBlock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LessonContentServiceServer).DeleteNoteBlock(ctx, req.(*DeleteContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LessonContentService_CreateHomeworkTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateHomeworkTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LessonContentServiceServer).CreateHomeworkTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LessonContentService_CreateHomeworkTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LessonContentServiceServer).CreateHomeworkTask(ctx, req.(*CreateHomeworkTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LessonContentService_UpdateHomeworkTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateHomeworkTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LessonContentServiceServer).UpdateHomeworkTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LessonContentService_UpdateHomeworkTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LessonContentServiceServer).UpdateHomeworkTask(ctx, req.(*UpdateHomeworkTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LessonContentService_DeleteHomeworkTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LessonContentServiceServer).DeleteHomeworkTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LessonContentService_DeleteHomeworkTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LessonContentServiceServer).DeleteHomeworkTask(ctx, req.(*DeleteContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LessonContentService_CreateCodeFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCodeFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LessonContentServiceServer).CreateCodeFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LessonContentService_CreateCodeFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LessonContentServiceServer).CreateCodeFile(ctx, req.(*CreateCodeFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LessonContentService_UpdateCodeFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCodeFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LessonContentServiceServer).UpdateCodeFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LessonContentService_UpdateCodeFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LessonContentServiceServer).UpdateCodeFile(ctx, req.(*UpdateCodeFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LessonContentService_DeleteCodeFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LessonContentServiceServer).DeleteCodeFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LessonContentService_DeleteCodeFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LessonContentServiceServer).DeleteCodeFile(ctx, req.(*DeleteContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LessonContentService_ReorderLessonContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReorderLessonContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LessonContentServiceServer).ReorderLessonContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LessonContentService_ReorderLessonContent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LessonContentServiceServer).ReorderLessonContent(ctx, req.(*ReorderLessonContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LessonContentService_ServiceDesc is the grpc.ServiceDesc for LessonContentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LessonContentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wantstudy.v1.LessonContentService",
	HandlerType: (*LessonContentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLessonWorkspace",
			Handler:    _LessonContentService_GetLessonWorkspace_Handler,
		},
		{
			MethodName: "CreateNoteBlock",
			Handler:    _LessonContentService_CreateNoteBlock_Handler,
		},
		{
			MethodName: "UpdateNoteBlock",
			Handler:    _LessonContentService_UpdateNoteBlock_Handler,
		},
		{
			MethodName: "DeleteNoteBlock",
			Handler:    _LessonContentService_DeleteNoteBlock_Handler,
		},
		{
			MethodName: "CreateHomeworkTask",
			Handler:    _LessonContentService_CreateHomeworkTask_Handler,
		},
		{
			MethodName: "UpdateHomeworkTask",
			Handler:    _LessonContentService_UpdateHomeworkTask_Handler,
		},
		{
			MethodName: "DeleteHomeworkTask",
			Handler:    _LessonContentService_DeleteHomeworkTask_Handler,
		},
		{
			MethodName: "CreateCodeFile",
			Handler:    _LessonContentService_CreateCodeFile_Handler,
		},
		{
			MethodName: "UpdateCodeFile",
			Handler:    _LessonContentService_UpdateCodeFile_Handler,
		},
		{
			MethodName: "DeleteCodeFile",
			Handler:    _LessonContentService_DeleteCodeFile_Handler,
		},
		{
			MethodName: "ReorderLessonContent",
			Handler:    _LessonContentService_ReorderLessonContent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wantstudy/v1/lesson_content.proto",
}
