// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: wantstudy/v1/lesson_content.proto

package wantstudyv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NoteBlockType int32

const (
	NoteBlockType_NOTE_BLOCK_TYPE_UNSPECIFIED NoteBlockType = 0
	NoteBlockType_NOTE_BLOCK_TYPE_TEXT        NoteBlockType = 1
	NoteBlockType_NOTE_BLOCK_TYPE_DEFINITION  NoteBlockType = 2
	NoteBlockType_NOTE_BLOCK_TYPE_CLAIM       NoteBlockType = 3
	NoteBlockType_NOTE_BLOCK_TYPE_QUOTE       NoteBlockType = 4
	NoteBlockType_NOTE_BLOCK_TYPE_EXAMPLE     NoteBlockType = 5
	NoteBlockType_NOTE_BLOCK_TYPE_QUESTION    NoteBlockType = 6
	NoteBlockType_NOTE_BLOCK_TYPE_SUMMARY     NoteBlockType = 7
)

// Enum value maps for NoteBlockType.
var (
	NoteBlockType_name = map[int32]string{
		0: "NOTE_BLOCK_TYPE_UNSPECIFIED",
		1: "NOTE_BLOCK_TYPE_TEXT",
		2: "NOTE_BLOCK_TYPE_DEFINITION",
		3: "NOTE_BLOCK_TYPE_CLAIM",
		4: "NOTE_BLOCK_TYPE_QUOTE",
		5: "NOTE_BLOCK_TYPE_EXAMPLE",
		6: "NOTE_BLOCK_TYPE_QUESTION",
		7: "NOTE_BLOCK_TYPE_SUMMARY",
	}
	NoteBlockType_value = map[string]int32{
		"NOTE_BLOCK_TYPE_UNSPECIFIED": 0,
		"NOTE_BLOCK_TYPE_TEXT":        1,
		"NOTE_BLOCK_TYPE_DEFINITION":  2,
		"NOTE_BLOCK_TYPE_CLAIM":       3,
		"NOTE_BLOCK_TYPE_QUOTE":       4,
		"NOTE_BLOCK_TYPE_EXAMPLE":     5,
		"NOTE_BLOCK_TYPE_QUESTION":    6,
		"NOTE_BLOCK_TYPE_SUMMARY":     7,
	}
)

func (x NoteBlockType) Enum() *NoteBlockType {
	p := new(NoteBlockType)
	*p = x
	return p
}

func (x NoteBlockType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NoteBlockType) Descriptor() protoreflect.EnumDescriptor {
	return file_wantstudy_v1_lesson_content_proto_enumTypes[0].Descriptor()
}

func (NoteBlockType) Type() protoreflect.EnumType {
	return &file_wantstudy_v1_lesson_content_proto_enumTypes[0]
}

func (x NoteBlockType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NoteBlockType.Descriptor instead.
func (NoteBlockType) EnumDescriptor() ([]byte, []int) {
	return file_wantstudy_v1_lesson_content_proto_rawDescGZIP(), []int{0}
}

type HomeworkStatus int32

const (
	HomeworkStatus_HOMEWORK_STATUS_UNSPECIFIED HomeworkStatus = 0
	HomeworkStatus_HOMEWORK_STATUS_TODO        HomeworkStatus = 1
	HomeworkStatus_HOMEWORK_STATUS_DONE        HomeworkStatus = 2
)

// Enum value maps for HomeworkStatus.
var (
	HomeworkStatus_name = map[int32]string{
		0: "HOMEWORK_STATUS_UNSPECIFIED",
		1: "HOMEWORK_STATUS_TODO",
		2: "HOMEWORK_STATUS_DONE",
	}
	HomeworkStatus_value = map[string]int32{
		"HOMEWORK_STATUS_UNSPECIFIED": 0,
		"HOMEWORK_STATUS_TODO":        1,
		"HOMEWORK_STATUS_DONE":        2,
	}
)

func (x HomeworkStatus) Enum() *HomeworkStatus {
	p := new(HomeworkStatus)
	*p = x
	return p
}

func (x HomeworkStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HomeworkStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_wantstudy_v1_lesson_content_proto_enumTypes[1].Descriptor()
}

func (HomeworkStatus) Type() protoreflect.EnumType {
	return &file_wantstudy_v1_lesson_content_proto_enumTypes[1]
}

func (x HomeworkStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HomeworkStatus.Descriptor instead.
func (HomeworkStatus) EnumDescriptor() ([]byte, []int) {
	return file_wantstudy_v1_lesson_content_proto_rawDescGZIP(), []int{1}
}

type NoteBlock struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StudyId        string                 `protobuf:"bytes,2,opt,name=study_id,json=studyId,proto3" json:"study_id,omitempty"`
	LessonId       string                 `protobuf:"bytes,3,opt,name=lesson_id,json=lessonId,proto3" json:"lesson_id,omitempty"`
	Type           NoteBlockType          `protobuf:"varint,4,opt,name=type,proto3,enum=wantstudy.v1.NoteBlockType" json:"type,omitempty"`
	Markdown       string                 `protobuf:"bytes,5,opt,name=markdown,proto3" json:"markdown,omitempty"`
	SourceUrl      string                 `protobuf:"bytes,6,opt,name=source_url,json=sourceUrl,proto3" json:"source_url,omitempty"`
	SourcePosition string                 `protobuf:"bytes,7,opt,name=source_position,json=sourcePosition,proto3" json:"source_position,omitempty"`
	Position       int32                  `protobuf:"varint,8,opt,name=position,proto3" json:"position,omitempty"`
	Version        int64                  `protobuf:"varint,9,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NoteBlock) Reset() {
	*x = NoteBlock{}
	mi := &file_wantstudy_v1_lesson_content_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoteBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoteBlock) ProtoMessage() {}

func (x *NoteBlock) ProtoReflect() protoreflect.Message {
	mi := &file_wantstudy_v1_lesson_content_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoteBlock.ProtoReflect.Descriptor instead.
func (*NoteBlock) Descriptor() ([]byte, []int) {
	return file_wantstudy_v1_lesson_content_proto_rawDescGZIP(), []int{0}
}

func (x *NoteBlock) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NoteBlock) GetStudyId() string {
	if x != nil {
		return x.StudyId
	}
	return ""
}

func (x *NoteBlock) GetLessonId() string {
	if x != nil {
		return x.LessonId
	}
	return ""
}

func (x *NoteBlock) GetType() NoteBlockType {
	if x != nil {
		return x.Type
	}
	return NoteBlockType_NOTE_BLOCK_TYPE_UNSPECIFIED
}

func (x *NoteBlock) GetMarkdown() string {
	if x != nil {
		return x.Markdown
	}
	return ""
}

func (x *NoteBlock) GetSourceUrl() string {
	if x != nil {
		return x.SourceUrl
	}
	return ""
}

func (x *NoteBlock) GetSourcePosition() string {
	if x != nil {
		return x.SourcePosition
	}
	return ""
}

func (x *NoteBlock) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *NoteBlock) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type HomeworkTask struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StudyId          string                 `protobuf:"bytes,2,opt,name=study_id,json=studyId,proto3" json:"study_id,omitempty"`
	LessonId         string                 `protobuf:"bytes,3,opt,name=lesson_id,json=lessonId,proto3" json:"lesson_id,omitempty"`
	PromptMarkdown   string                 `protobuf:"bytes,4,opt,name=prompt_markdown,json=promptMarkdown,proto3" json:"prompt_markdown,omitempty"`
	SolutionMarkdown string                 `protobuf:"bytes,5,opt,name=solution_markdown,json=solutionMarkdown,proto3" json:"solution_markdown,omitempty"`
	Status           HomeworkStatus         `protobuf:"varint,6,opt,name=status,proto3,enum=wantstudy.v1.HomeworkStatus" json:"status,omitempty"`
	DueAtEpochMillis *int64                 `protobuf:"varint,7,opt,name=due_at_epoch_millis,json=dueAtEpochMillis,proto3,oneof" json:"due_at_epoch_millis,omitempty"`
	Position         int32                  `protobuf:"varint,8,opt,name=position,proto3" json:"position,omitempty"`
	Version          int64                  `protobuf:"varint,9,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HomeworkTask) Reset() {
	*x = HomeworkTask{}
	mi := &file_wantstudy_v1_lesson_content_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HomeworkTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HomeworkTask) ProtoMessage() {}

func (x *HomeworkTask) ProtoReflect() protoreflect.Message {
	mi := &file_wantstudy_v1_lesson_content_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HomeworkTask.ProtoReflect.Descriptor instead.
func (*HomeworkTask) Descriptor() ([]byte, []int) {
	return file_wantstudy_v1_lesson_content_proto_rawDescGZIP(), []int{1}
}

func (x *HomeworkTask) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HomeworkTask) GetStudyId() string {
	if x != nil {
		return x.StudyId
	}
	return ""
}

func (x *HomeworkTask) GetLessonId() string {
	if x != nil {
		return x.LessonId
	}
	return ""
}

func (x *HomeworkTask) GetPromptMarkdown() string {
	if x != nil {
		return x.PromptMarkdown
	}
	return ""
}

func (x *HomeworkTask) GetSolutionMarkdown() string {
	if x != nil {
		return x.SolutionMarkdown
	}
	return ""
}

func (x *HomeworkTask) GetStatus() HomeworkStatus {
	if x != nil {
		return x.Status
	}
	return HomeworkStatus_HOMEWORK_STATUS_UNSPECIFIED
}

func (x *HomeworkTask) GetDueAtEpochMillis() int64 {
	if x != nil && x.DueAtEpochMillis != nil {
		return *x.DueAtEpochMillis
	}
	return 0
}

func (x *HomeworkTask) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *HomeworkTask) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type CodeFile struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StudyId        string                 `protobuf:"bytes,2,opt,name=study_id,json=studyId,proto3" json:"study_id,omitempty"`
	LessonId       string                 `protobuf:"bytes,3,opt,name=lesson_id,json=lessonId,proto3" json:"lesson_id,omitempty"`
	HomeworkTaskId *string                `protobuf:"bytes,4,opt,name=homework_task_id,json=homeworkTaskId,proto3,oneof" json:"homework_task_id,omitempty"`
	RelativePath   string                 `protobuf:"bytes,5,opt,name=relative_path,json=relativePath,proto3" json:"relative_path,omitempty"`
	Language       string                 `protobuf:"bytes,6,opt,name=language,proto3" json:"language,omitempty"`
	Content        string                 `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`
	Version        int64                  `protobuf:"varint,8,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CodeFile) Reset() {
	*x = CodeFile{}
	mi := &file_wantstudy_v1_lesson_content_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CodeFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CodeFile) ProtoMessage() {}

func (x *CodeFile) ProtoReflect() protoreflect.Message {
	mi := &file_wantstudy_v1_lesson_content_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CodeFile.ProtoReflect.Descriptor instead.
func (*CodeFile) Descriptor() ([]byte, []int) {
	return file_wantstudy_v1_lesson_content_proto_rawDescGZIP(), []int{2}
}

func (x *CodeFile) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CodeFile) GetStudyId() string {
	if x != nil {
		return x.StudyId
	}
	return ""
}

func (x *CodeFile) GetLessonId() string {
	if x != nil {
		return x.LessonId
	}
	return ""
}

func (x *CodeFile) GetHomeworkTaskId() string {
	if x != nil && x.HomeworkTaskId != nil {
		return *x.HomeworkTaskId
	}
	return ""
}

func (x *CodeFile) GetRelativePath() string {
	if x != nil {
		return x.RelativePath
	}
	return ""
}

func (x *CodeFile) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *CodeFile) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CodeFile) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type GetLessonWorkspaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LessonId      string                 `protobuf:"bytes,1,opt,name=lesson_id,json=lessonId,proto3" json:"lesson_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLessonWorkspaceRequest) Reset() {
	*x = GetLessonWorkspaceRequest{}
	mi := &file_wantstudy_v1_lesson_content_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLessonWorkspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLessonWorkspaceRequest) ProtoMessage() {}

func (x *GetLessonWorkspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wantstudy_v1_lesson_content_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLessonWorkspaceRequest.ProtoReflect.Descriptor instead.
func (*GetLessonWorkspaceRequest) Descriptor() ([]byte, []int) {
	return file_wantstudy_v1_lesson_content_proto_rawDescGZIP(), []int{3}
}

func (x *GetLessonWorkspaceRequest) GetLessonId() string {
	if x != nil {
		return x.LessonId
	}
	return ""
}

type LessonWorkspace struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lesson        *Lesson                `protobuf:"bytes,1,opt,name=lesson,proto3" json:"lesson,omitempty"`
	Blocks        []*NoteBlock           `protobuf:"bytes,2,rep,name=blocks,proto3" json:"blocks,omitempty"`
	Tasks         []*HomeworkTask        `protobuf:"bytes,3,rep,name=tasks,proto3" json:"tasks,omitempty"`
	Files         []*CodeFile            `protobuf:"bytes,4,rep,name=files,proto3" json:"files,omitempty"`
	ConceptIds    []string               `protobuf:"bytes,5,rep,name=concept_ids,json=conceptIds,proto3" json:"concept_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LessonWorkspace) Reset() {
	*x = LessonWorkspace{}
	mi := &file_wantstudy_v1_lesson_content_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LessonWorkspace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LessonWorkspace) ProtoMessage() {}

func (x *LessonWorkspace) ProtoReflect() protoreflect.Message {
	mi := &file_wantstudy_v1_lesson_content_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LessonWorkspace.ProtoReflect.Descriptor instead.
func (*LessonWorkspace) Descriptor() ([]byte, []int) {
	return file_wantstudy_v1_lesson_content_proto_rawDescGZIP(), []int{4}
}

func (x *LessonWorkspace) GetLesson() *Lesson {
	if x != nil {
		return x.Lesson
	}
	return nil
}

func (x *LessonWorkspace) GetBlocks() []*NoteBlock {
	if x != nil {
		return x.Blocks
	}
	return nil
}

func (x *LessonWorkspace) GetTasks() []*HomeworkTask {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *LessonWorkspace) GetFiles() []*CodeFile {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *LessonWorkspace) GetConceptIds() []string {
	if x != nil {
		return x.ConceptIds
	}
	return nil
}

type CreateNoteBlockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Block         *NoteBlock             `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNoteBlockRequest) Reset() {
	*x = CreateNoteBlockRequest{}
	mi := &file_wantstudy_v1_lesson_content_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNoteBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNoteBlockRequest) ProtoMessage() {}

func (x *CreateNoteBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wantstudy_v1_lesson_content_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNoteBlockRequest.ProtoReflect.Descriptor instead.
func (*CreateNoteBlockRequest) Descriptor() ([]byte, []int) {
	return file_wantstudy_v1_lesson_content_proto_rawDescGZIP(), []int{5}
}

func (x *CreateNoteBlockRequest) GetBlock() *NoteBlock {
	if x != nil {
		return x.Block
	}
	return nil
}

type UpdateNoteBlockRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Block           *NoteBlock             `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	ExpectedVersion int64                  `protobuf:"varint,2,opt,name=expected_version,json=expectedVersion,proto3" json:"expected_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateNoteBlockRequest) Reset() {
	*x = UpdateNoteBlockRequest{}
	mi := &file_wantstudy_v1_lesson_content_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNoteBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNoteBlockRequest) ProtoMessage() {}

func (x *UpdateNoteBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wantstudy_v1_lesson_content_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNoteBlockRequest.ProtoReflect.Descriptor instead.
func (*UpdateNoteBlockRequest) Descriptor() ([]byte, []int) {
	return file_wantstudy_v1_lesson_content_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateNoteBlockRequest) GetBlock() *NoteBlock {
	if x != nil {
		return x.Block
	}
	return nil
}

func (x *UpdateNoteBlockRequest) GetExpectedVersion() int64 {
	if x != nil {
		return x.ExpectedVersion
	}
	return 0
}

type CreateHomeworkTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *HomeworkTask          `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateHomeworkTaskRequest) Reset() {
	*x = CreateHomeworkTaskRequest{}
	mi := &file_wantstudy_v1_lesson_content_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateHomeworkTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHomeworkTaskRequest) ProtoMessage() {}

func (x *CreateHomeworkTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wantstudy_v1_lesson_content_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHomeworkTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateHomeworkTaskRequest) Descriptor() ([]byte, []int) {
	return file_wantstudy_v1_lesson_content_proto_rawDescGZIP(), []int{7}
}

func (x *CreateHomeworkTaskRequest) GetTask() *HomeworkTask {
	if x != nil {
		return x.Task
	}
	return nil
}

type UpdateHomeworkTaskRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Task            *HomeworkTask          `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	ExpectedVersion int64                  `protobuf:"varint,2,opt,name=expected_version,json=expectedVersion,proto3" json:"expected_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateHomeworkTaskRequest) Reset() {
	*x = UpdateHomeworkTaskRequest{}
	mi := &file_wantstudy_v1_lesson_content_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateHomeworkTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateHomeworkTaskRequest) ProtoMessage() {}

func (x *UpdateHomeworkTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wantstudy_v1_lesson_content_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateHomeworkTaskRequest.ProtoReflect.Descriptor instead.
func (*UpdateHomeworkTaskRequest) Descriptor() ([]byte, []int) {
	return file_wantstudy_v1_lesson_content_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateHomeworkTaskRequest) GetTask() *HomeworkTask {
	if x != nil {
		return x.Task
	}
	return nil
}

func (x *UpdateHomeworkTaskRequest) GetExpectedVersion() int64 {
	if x != nil {
		return x.ExpectedVersion
	}
	return 0
}

type CreateCodeFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          *CodeFile              `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCodeFileRequest) Reset() {
	*x = CreateCodeFileRequest{}
	mi := &file_wantstudy_v1_lesson_content_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCodeFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCodeFileRequest) ProtoMessage() {}

func (x *CreateCodeFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wantstudy_v1_lesson_content_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCodeFileRequest.ProtoReflect.Descriptor instead.
func (*CreateCodeFileRequest) Descriptor() ([]byte, []int) {
	return file_wantstudy_v1_lesson_content_proto_rawDescGZIP(), []int{9}
}

func (x *CreateCodeFileRequest) GetFile() *CodeFile {
	if x != nil {
		return x.File
	}
	return nil
}

type UpdateCodeFileRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	File            *CodeFile              `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	ExpectedVersion int64                  `protobuf:"varint,2,opt,name=expected_version,json=expectedVersion,proto3" json:"expected_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateCodeFileRequest) Reset() {
	*x = UpdateCodeFileRequest{}
	mi := &file_wantstudy_v1_lesson_content_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCodeFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCodeFileRequest) ProtoMessage() {}

func (x *UpdateCodeFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wantstudy_v1_lesson_content_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCodeFileRequest.ProtoReflect.Descriptor instead.
func (*UpdateCodeFileRequest) Descriptor() ([]byte, []int) {
	return file_wantstudy_v1_lesson_content_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateCodeFileRequest) GetFile() *CodeFile {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *UpdateCodeFileRequest) GetExpectedVersion() int64 {
	if x != nil {
		return x.ExpectedVersion
	}
	return 0
}

type DeleteContentRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ExpectedVersion int64                  `protobuf:"varint,2,opt,name=expected_version,json=expectedVersion,proto3" json:"expected_version,omitempty"`
	Confirmed       bool                   `protobuf:"varint,3,opt,name=confirmed,proto3" json:"confirmed,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DeleteContentRequest) Reset() {
	*x = DeleteContentRequest{}
	mi := &file_wantstudy_v1_lesson_content_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteContentRequest) ProtoMessage() {}

func (x *DeleteContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wantstudy_v1_lesson_content_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteContentRequest.ProtoReflect.Descriptor instead.
func (*DeleteContentRequest) Descriptor() ([]byte, []int) {
	return file_wantstudy_v1_lesson_content_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteContentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteContentRequest) GetExpectedVersion() int64 {
	if x != nil {
		return x.ExpectedVersion
	}
	return 0
}

func (x *DeleteContentRequest) GetConfirmed() bool {
	if x != nil {
		return x.Confirmed
	}
	return false
}

type DeleteContentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteContentResponse) Reset() {
	*x = DeleteContentResponse{}
	mi := &file_wantstudy_v1_lesson_content_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteContentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteContentResponse) ProtoMessage() {}

func (x *DeleteContentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wantstudy_v1_lesson_content_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteContentResponse.ProtoReflect.Descriptor instead.
func (*DeleteContentResponse) Descriptor() ([]byte, []int) {
	return file_wantstudy_v1_lesson_content_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteContentResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ReorderLessonContentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LessonId      string                 `protobuf:"bytes,1,opt,name=lesson_id,json=lessonId,proto3" json:"lesson_id,omitempty"`
	Blocks        []*ReorderItem         `protobuf:"bytes,2,rep,name=blocks,proto3" json:"blocks,omitempty"`
	Tasks         []*ReorderItem         `protobuf:"bytes,3,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReorderLessonContentRequest) Reset() {
	*x = ReorderLessonContentRequest{}
	mi := &file_wantstudy_v1_lesson_content_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReorderLessonContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReorderLessonContentRequest) ProtoMessage() {}

func (x *ReorderLessonContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wantstudy_v1_lesson_content_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReorderLessonContentRequest.ProtoReflect.Descriptor instead.
func (*ReorderLessonContentRequest) Descriptor() ([]byte, []int) {
	return file_wantstudy_v1_lesson_content_proto_rawDescGZIP(), []int{13}
}

func (x *ReorderLessonContentRequest) GetLessonId() string {
	if x != nil {
		return x.LessonId
	}
	return ""
}

func (x *ReorderLessonContentRequest) GetBlocks() []*ReorderItem {
	if x != nil {
		return x.Blocks
	}
	return nil
}

func (x *ReorderLessonContentRequest) GetTasks() []*ReorderItem {
	if x != nil {
		return x.Tasks
	}
	return nil
}

var File_wantstudy_v1_lesson_content_proto protoreflect.FileDescriptor

const file_wantstudy_v1_lesson_content_proto_rawDesc = "" +
	"\n" +
	"!wantstudy/v1/lesson_content.proto\x12\fwantstudy.v1\x1a\x18wantstudy/v1/study.proto\"\x9e\x02\n" +
	"\tNoteBlock\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bstudy_id\x18\x02 \x01(\tR\astudyId\x12\x1b\n" +
	"\tlesson_id\x18\x03 \x01(\tR\blessonId\x12/\n" +
	"\x04type\x18\x04 \x01(\x0e2\x1b.wantstudy.v1.NoteBlockTypeR\x04type\x12\x1a\n" +
	"\bmarkdown\x18\x05 \x01(\tR\bmarkdown\x12\x1d\n" +
	"\n" +
	"source_url\x18\x06 \x01(\tR\tsourceUrl\x12'\n" +
	"\x0fsource_position\x18\a \x01(\tR\x0esourcePosition\x12\x1a\n" +
	"\bposition\x18\b \x01(\x05R\bposition\x12\x18\n" +
	"\aversion\x18\t \x01(\x03R\aversion\"\xe4\x02\n" +
	"\fHomeworkTask\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bstudy_id\x18\x02 \x01(\tR\astudyId\x12\x1b\n" +
	"\tlesson_id\x18\x03 \x01(\tR\blessonId\x12'\n" +
	"\x0fprompt_markdown\x18\x04 \x01(\tR\x0epromptMarkdown\x12+\n" +
	"\x11solution_markdown\x18\x05 \x01(\tR\x10solutionMarkdown\x124\n" +
	"\x06status\x18\x06 \x01(\x0e2\x1c.wantstudy.v1.HomeworkStatusR\x06status\x122\n" +
	"\x13due_at_epoch_millis\x18\a \x01(\x03H\x00R\x10dueAtEpochMillis\x88\x01\x01\x12\x1a\n" +
	"\bposition\x18\b \x01(\x05R\bposition\x12\x18\n" +
	"\aversion\x18\t \x01(\x03R\aversionB\x16\n" +
	"\x14_due_at_epoch_millis\"\x8b\x02\n" +
	"\bCodeFile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bstudy_id\x18\x02 \x01(\tR\astudyId\x12\x1b\n" +
	"\tlesson_id\x18\x03 \x01(\tR\blessonId\x12-\n" +
	"\x10homework_task_id\x18\x04 \x01(\tH\x00R\x0ehomeworkTaskId\x88\x01\x01\x12#\n" +
	"\rrelative_path\x18\x05 \x01(\tR\frelativePath\x12\x1a\n" +
	"\blanguage\x18\x06 \x01(\tR\blanguage\x12\x18\n" +
	"\acontent\x18\a \x01(\tR\acontent\x12\x18\n" +
	"\aversion\x18\b \x01(\x03R\aversionB\x13\n" +
	"\x11_homework_task_id\"8\n" +
	"\x19GetLessonWorkspaceRequest\x12\x1b\n" +
	"\tlesson_id\x18\x01 \x01(\tR\blessonId\"\xf1\x01\n" +
	"\x0fLessonWorkspace\x12,\n" +
	"\x06lesson\x18\x01 \x01(\v2\x14.wantstudy.v1.LessonR\x06lesson\x12/\n" +
	"\x06blocks\x18\x02 \x03(\v2\x17.wantstudy.v1.NoteBlockR\x06blocks\x120\n" +
	"\x05tasks\x18\x03 \x03(\v2\x1a.wantstudy.v1.HomeworkTaskR\x05tasks\x12,\n" +
	"\x05files\x18\x04 \x03(\v2\x16.wantstudy.v1.CodeFileR\x05files\x12\x1f\n" +
	"\vconcept_ids\x18\x05 \x03(\tR\n" +
	"conceptIds\"G\n" +
	"\x16CreateNoteBlockRequest\x12-\n" +
	"\x05block\x18\x01 \x01(\v2\x17.wantstudy.v1.NoteBlockR\x05block\"r\n" +
	"\x16UpdateNoteBlockRequest\x12-\n" +
	"\x05block\x18\x01 \x01(\v2\x17.wantstudy.v1.NoteBlockR\x05block\x12)\n" +
	"\x10expected_version\x18\x02 \x01(\x03R\x0fexpectedVersion\"K\n" +
	"\x19CreateHomeworkTaskRequest\x12.\n" +
	"\x04task\x18\x01 \x01(\v2\x1a.wantstudy.v1.HomeworkTaskR\x04task\"v\n" +
	"\x19UpdateHomeworkTaskRequest\x12.\n" +
	"\x04task\x18\x01 \x01(\v2\x1a.wantstudy.v1.HomeworkTaskR\x04task\x12)\n" +
	"\x10expected_version\x18\x02 \x01(\x03R\x0fexpectedVersion\"C\n" +
	"\x15CreateCodeFileRequest\x12*\n" +
	"\x04file\x18\x01 \x01(\v2\x16.wantstudy.v1.CodeFileR\x04file\"n\n" +
	"\x15UpdateCodeFileRequest\x12*\n" +
	"\x04file\x18\x01 \x01(\v2\x16.wantstudy.v1.CodeFileR\x04file\x12)\n" +
	"\x10expected_version\x18\x02 \x01(\x03R\x0fexpectedVersion\"o\n" +
	"\x14DeleteContentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12)\n" +
	"\x10expected_version\x18\x02 \x01(\x03R\x0fexpectedVersion\x12\x1c\n" +
	"\tconfirmed\x18\x03 \x01(\bR\tconfirmed\"'\n" +
	"\x15DeleteContentResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x9e\x01\n" +
	"\x1bReorderLessonContentRequest\x12\x1b\n" +
	"\tlesson_id\x18\x01 \x01(\tR\blessonId\x121\n" +
	"\x06blocks\x18\x02 \x03(\v2\x19.wantstudy.v1.ReorderItemR\x06blocks\x12/\n" +
	"\x05tasks\x18\x03 \x03(\v2\x19.wantstudy.v1.ReorderItemR\x05tasks*\xf8\x01\n" +
	"\rNoteBlockType\x12\x1f\n" +
	"\x1bNOTE_BLOCK_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14NOTE_BLOCK_TYPE_TEXT\x10\x01\x12\x1e\n" +
	"\x1aNOTE_BLOCK_TYPE_DEFINITION\x10\x02\x12\x19\n" +
	"\x15NOTE_BLOCK_TYPE_CLAIM\x10\x03\x12\x19\n" +
	"\x15NOTE_BLOCK_TYPE_QUOTE\x10\x04\x12\x1b\n" +
	"\x17NOTE_BLOCK_TYPE_EXAMPLE\x10\x05\x12\x1c\n" +
	"\x18NOTE_BLOCK_TYPE_QUESTION\x10\x06\x12\x1b\n" +
	"\x17NOTE_BLOCK_TYPE_SUMMARY\x10\a*e\n" +
	"\x0eHomeworkStatus\x12\x1f\n" +
	"\x1bHOMEWORK_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14HOMEWORK_STATUS_TODO\x10\x01\x12\x18\n" +
	"\x14HOMEWORK_STATUS_DONE\x10\x022\xe4\a\n" +
	"\x14LessonContentService\x12\\\n" +
	"\x12GetLessonWorkspace\x12'.wantstudy.v1.GetLessonWorkspaceRequest\x1a\x1d.wantstudy.v1.LessonWorkspace\x12P\n" +
	"\x0fCreateNoteBlock\x12$.wantstudy.v1.CreateNoteBlockRequest\x1a\x17.wantstudy.v1.NoteBlock\x12P\n" +
	"\x0fUpdateNoteBlock\x12$.wantstudy.v1.UpdateNoteBlockRequest\x1a\x17.wantstudy.v1.NoteBlock\x12Z\n" +
	"\x0fDeleteNoteBlock\x12\".wantstudy.v1.DeleteContentRequest\x1a#.wantstudy.v1.DeleteContentResponse\x12Y\n" +
	"\x12CreateHomeworkTask\x12'.wantstudy.v1.CreateHomeworkTaskRequest\x1a\x1a.wantstudy.v1.HomeworkTask\x12Y\n" +
	"\x12UpdateHomeworkTask\x12'.wantstudy.v1.UpdateHomeworkTaskRequest\x1a\x1a.wantstudy.v1.HomeworkTask\x12]\n" +
	"\x12DeleteHomeworkTask\x12\".wantstudy.v1.DeleteContentRequest\x1a#.wantstudy.v1.DeleteContentResponse\x12M\n" +
	"\x0eCreateCodeFile\x12#.wantstudy.v1.CreateCodeFileRequest\x1a\x16.wantstudy.v1.CodeFile\x12M\n" +
	"\x0eUpdateCodeFile\x12#.wantstudy.v1.UpdateCodeFileRequest\x1a\x16.wantstudy.v1.CodeFile\x12Y\n" +
	"\x0eDeleteCodeFile\x12\".wantstudy.v1.DeleteContentRequest\x1a#.wantstudy.v1.DeleteContentResponse\x12`\n" +
	"\x14ReorderLessonContent\x12).wantstudy.v1.ReorderLessonContentRequest\x1a\x1d.wantstudy.v1.LessonWorkspaceBSZQgithub.com/pchkauu/want-study/service/api/internal/proto/wantstudy/v1;wantstudyv1b\x06proto3"

var (
	file_wantstudy_v1_lesson_content_proto_rawDescOnce sync.Once
	file_wantstudy_v1_lesson_content_proto_rawDescData []byte
)

func file_wantstudy_v1_lesson_content_proto_rawDescGZIP() []byte {
	file_wantstudy_v1_lesson_content_proto_rawDescOnce.Do(func() {
		file_wantstudy_v1_lesson_content_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wantstudy_v1_lesson_content_proto_rawDesc), len(file_wantstudy_v1_lesson_content_proto_rawDesc)))
	})
	return file_wantstudy_v1_lesson_content_proto_rawDescData
}

var file_wantstudy_v1_lesson_content_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_wantstudy_v1_lesson_content_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_wantstudy_v1_lesson_content_proto_goTypes = []any{
	(NoteBlockType)(0),                  // 0: wantstudy.v1.NoteBlockType
	(HomeworkStatus)(0),                 // 1: wantstudy.v1.HomeworkStatus
	(*NoteBlock)(nil),                   // 2: wantstudy.v1.NoteBlock
	(*HomeworkTask)(nil),                // 3: wantstudy.v1.HomeworkTask
	(*CodeFile)(nil),                    // 4: wantstudy.v1.CodeFile
	(*GetLessonWorkspaceRequest)(nil),   // 5: wantstudy.v1.GetLessonWorkspaceRequest
	(*LessonWorkspace)(nil),             // 6: wantstudy.v1.LessonWorkspace
	(*CreateNoteBlockRequest)(nil),      // 7: wantstudy.v1.CreateNoteBlockRequest
	(*UpdateNoteBlockRequest)(nil),      // 8: wantstudy.v1.UpdateNoteBlockRequest
	(*CreateHomeworkTaskRequest)(nil),   // 9: wantstudy.v1.CreateHomeworkTaskRequest
	(*UpdateHomeworkTaskRequest)(nil),   // 10: wantstudy.v1.UpdateHomeworkTaskRequest
	(*CreateCodeFileRequest)(nil),       // 11: wantstudy.v1.CreateCodeFileRequest
	(*UpdateCodeFileRequest)(nil),       // 12: wantstudy.v1.UpdateCodeFileRequest
	(*DeleteContentRequest)(nil),        // 13: wantstudy.v1.DeleteContentRequest
	(*DeleteContentResponse)(nil),       // 14: wantstudy.v1.DeleteContentResponse
	(*ReorderLessonContentRequest)(nil), // 15: wantstudy.v1.ReorderLessonContentRequest
	(*Lesson)(nil),                      // 16: wantstudy.v1.Lesson
	(*ReorderItem)(nil),                 // 17: wantstudy.v1.ReorderItem
}
var file_wantstudy_v1_lesson_content_proto_depIdxs = []int32{
	0,  // 0: wantstudy.v1.NoteBlock.type:type_name -> wantstudy.v1.NoteBlockType
	1,  // 1: wantstudy.v1.HomeworkTask.status:type_name -> wantstudy.v1.HomeworkStatus
	16, // 2: wantstudy.v1.LessonWorkspace.lesson:type_name -> wantstudy.v1.Lesson
	2,  // 3: wantstudy.v1.LessonWorkspace.blocks:type_name -> wantstudy.v1.NoteBlock
	3,  // 4: wantstudy.v1.LessonWorkspace.tasks:type_name -> wantstudy.v1.HomeworkTask
	4,  // 5: wantstudy.v1.LessonWorkspace.files:type_name -> wantstudy.v1.CodeFile
	2,  // 6: wantstudy.v1.CreateNoteBlockRequest.block:type_name -> wantstudy.v1.NoteBlock
	2,  // 7: wantstudy.v1.UpdateNoteBlockRequest.block:type_name -> wantstudy.v1.NoteBlock
	3,  // 8: wantstudy.v1.CreateHomeworkTaskRequest.task:type_name -> wantstudy.v1.HomeworkTask
	3,  // 9: wantstudy.v1.UpdateHomeworkTaskRequest.task:type_name -> wantstudy.v1.HomeworkTask
	4,  // 10: wantstudy.v1.CreateCodeFileRequest.file:type_name -> wantstudy.v1.CodeFile
	4,  // 11: wantstudy.v1.UpdateCodeFileRequest.file:type_name -> wantstudy.v1.CodeFile
	17, // 12: wantstudy.v1.ReorderLessonContentRequest.blocks:type_name -> wantstudy.v1.ReorderItem
	17, // 13: wantstudy.v1.ReorderLessonContentRequest.tasks:type_name -> wantstudy.v1.ReorderItem
	5,  // 14: wantstudy.v1.LessonContentService.GetLessonWorkspace:input_type -> wantstudy.v1.GetLessonWorkspaceRequest
	7,  // 15: wantstudy.v1.LessonContentService.CreateNoteBlock:input_type -> wantstudy.v1.CreateNoteBlockRequest
	8,  // 16: wantstudy.v1.LessonContentService.UpdateNoteBlock:input_type -> wantstudy.v1.UpdateNoteBlockRequest
	13, // 17: wantstudy.v1.LessonContentService.DeleteNoteBlock:input_type -> wantstudy.v1.DeleteContentRequest
	9,  // 18: wantstudy.v1.LessonContentService.CreateHomeworkTask:input_type -> wantstudy.v1.CreateHomeworkTaskRequest
	10, // 19: wantstudy.v1.LessonContentService.UpdateHomeworkTask:input_type -> wantstudy.v1.UpdateHomeworkTaskRequest
	13, // 20: wantstudy.v1.LessonContentService.DeleteHomeworkTask:input_type -> wantstudy.v1.DeleteContentRequest
	11, // 21: wantstudy.v1.LessonContentService.CreateCodeFile:input_type -> wantstudy.v1.CreateCodeFileRequest
	12, // 22: wantstudy.v1.LessonContentService.UpdateCodeFile:input_type -> wantstudy.v1.UpdateCodeFileRequest
	13, // 23: wantstudy.v1.LessonContentService.DeleteCodeFile:input_type -> wantstudy.v1.DeleteContentRequest
	15, // 24: wantstudy.v1.LessonContentService.ReorderLessonContent:input_type -> wantstudy.v1.ReorderLessonContentRequest
	6,  // 25: wantstudy.v1.LessonContentService.GetLessonWorkspace:output_type -> wantstudy.v1.LessonWorkspace
	2,  // 26: wantstudy.v1.LessonContentService.CreateNoteBlock:output_type -> wantstudy.v1.NoteBlock
	2,  // 27: wantstudy.v1.LessonContentService.UpdateNoteBlock:output_type -> wantstudy.v1.NoteBlock
	14, // 28: wantstudy.v1.LessonContentService.DeleteNoteBlock:output_type -> wantstudy.v1.DeleteContentResponse
	3,  // 29: wantstudy.v1.LessonContentService.CreateHomeworkTask:output_type -> wantstudy.v1.HomeworkTask
	3,  // 30: wantstudy.v1.LessonContentService.UpdateHomeworkTask:output_type -> wantstudy.v1.HomeworkTask
	14, // 31: wantstudy.v1.LessonContentService.DeleteHomeworkTask:output_type -> wantstudy.v1.DeleteContentResponse
	4,  // 32: wantstudy.v1.LessonContentService.CreateCodeFile:output_type -> wantstudy.v1.CodeFile
	4,  // 33: wantstudy.v1.LessonContentService.UpdateCodeFile:output_type -> wantstudy.v1.CodeFile
	14, // 34: wantstudy.v1.LessonContentService.DeleteCodeFile:output_type -> wantstudy.v1.DeleteContentResponse
	6,  // 35: wantstudy.v1.LessonContentService.ReorderLessonContent:output_type -> wantstudy.v1.LessonWorkspace
	25, // [25:36] is the sub-list for method output_type
	14, // [14:25] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_wantstudy_v1_lesson_content_proto_init() }
func file_wantstudy_v1_lesson_content_proto_init() {
	if File_wantstudy_v1_lesson_content_proto != nil {
		return
	}
	file_wantstudy_v1_study_proto_init()
	file_wantstudy_v1_lesson_content_proto_msgTypes[1].OneofWrappers = []any{}
	file_wantstudy_v1_lesson_content_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wantstudy_v1_lesson_content_proto_rawDesc), len(file_wantstudy_v1_lesson_content_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wantstudy_v1_lesson_content_proto_goTypes,
		DependencyIndexes: file_wantstudy_v1_lesson_content_proto_depIdxs,
		EnumInfos:         file_wantstudy_v1_lesson_content_proto_enumTypes,
		MessageInfos:      file_wantstudy_v1_lesson_content_proto_msgTypes,
	}.Build()
	File_wantstudy_v1_lesson_content_proto = out.File
	file_wantstudy_v1_lesson_content_proto_goTypes = nil
	file_wantstudy_v1_lesson_content_proto_depIdxs = nil
}
