// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: wantstudy/v1/study.proto

package wantstudyv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StudyCatalogService_CreateStudy_FullMethodName           = "/wantstudy.v1.StudyCatalogService/CreateStudy"
	StudyCatalogService_GetStudy_FullMethodName              = "/wantstudy.v1.StudyCatalogService/GetStudy"
	StudyCatalogService_ListStudies_FullMethodName           = "/wantstudy.v1.StudyCatalogService/ListStudies"
	StudyCatalogService_UpdateStudy_FullMethodName           = "/wantstudy.v1.StudyCatalogService/UpdateStudy"
	StudyCatalogService_ArchiveStudy_FullMethodName          = "/wantstudy.v1.StudyCatalogService/ArchiveStudy"
	StudyCatalogService_RestoreStudy_FullMethodName          = "/wantstudy.v1.StudyCatalogService/RestoreStudy"
	StudyCatalogService_CreateLearningSource_FullMethodName  = "/wantstudy.v1.StudyCatalogService/CreateLearningSource"
	StudyCatalogService_UpdateLearningSource_FullMethodName  = "/wantstudy.v1.StudyCatalogService/UpdateLearningSource"
	StudyCatalogService_ArchiveLearningSource_FullMethodName = "/wantstudy.v1.StudyCatalogService/ArchiveLearningSource"
	StudyCatalogService_RestoreLearningSource_FullMethodName = "/wantstudy.v1.StudyCatalogService/RestoreLearningSource"
	StudyCatalogService_CreateSection_FullMethodName         = "/wantstudy.v1.StudyCatalogService/CreateSection"
	StudyCatalogService_UpdateSection_FullMethodName         = "/wantstudy.v1.StudyCatalogService/UpdateSection"
	StudyCatalogService_ArchiveSection_FullMethodName        = "/wantstudy.v1.StudyCatalogService/ArchiveSection"
	StudyCatalogService_RestoreSection_FullMethodName        = "/wantstudy.v1.StudyCatalogService/RestoreSection"
	StudyCatalogService_CreateLesson_FullMethodName          = "/wantstudy.v1.StudyCatalogService/CreateLesson"
	StudyCatalogService_UpdateLesson_FullMethodName          = "/wantstudy.v1.StudyCatalogService/UpdateLesson"
	StudyCatalogService_ArchiveLesson_FullMethodName         = "/wantstudy.v1.StudyCatalogService/ArchiveLesson"
	StudyCatalogService_RestoreLesson_FullMethodName         = "/wantstudy.v1.StudyCatalogService/RestoreLesson"
	StudyCatalogService_ChangeLessonStatus_FullMethodName    = "/wantstudy.v1.StudyCatalogService/ChangeLessonStatus"
	StudyCatalogService_GetMaterialTree_FullMethodName       = "/wantstudy.v1.StudyCatalogService/GetMaterialTree"
	StudyCatalogService_ReorderMaterial_FullMethodName       = "/wantstudy.v1.StudyCatalogService/ReorderMaterial"
	StudyCatalogService_GetDashboard_FullMethodName          = "/wantstudy.v1.StudyCatalogService/GetDashboard"
)

// StudyCatalogServiceClient is the client API for StudyCatalogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StudyCatalogServiceClient interface {
	CreateStudy(ctx context.Context, in *CreateStudyRequest, opts ...grpc.CallOption) (*Study, error)
	GetStudy(ctx context.Context, in *GetStudyRequest, opts ...grpc.CallOption) (*Study, error)
	ListStudies(ctx context.Context, in *ListStudiesRequest, opts ...grpc.CallOption) (*ListStudiesResponse, error)
	UpdateStudy(ctx context.Context, in *UpdateStudyRequest, opts ...grpc.CallOption) (*Study, error)
	ArchiveStudy(ctx context.Context, in *ChangeArchiveRequest, opts ...grpc.CallOption) (*Study, error)
	RestoreStudy(ctx context.Context, in *ChangeArchiveRequest, opts ...grpc.CallOption) (*Study, error)
	CreateLearningSource(ctx context.Context, in *CreateLearningSourceRequest, opts ...grpc.CallOption) (*LearningSource, error)
	UpdateLearningSource(ctx context.Context, in *UpdateLearningSourceRequest, opts ...grpc.CallOption) (*LearningSource, error)
	ArchiveLearningSource(ctx context.Context, in *ChangeArchiveRequest, opts ...grpc.CallOption) (*LearningSource, error)
	RestoreLearningSource(ctx context.Context, in *ChangeArchiveRequest, opts ...grpc.CallOption) (*LearningSource, error)
	CreateSection(ctx context.Context, in *CreateSectionRequest, opts ...grpc.CallOption) (*Section, error)
	UpdateSection(ctx context.Context, in *UpdateSectionRequest, opts ...grpc.CallOption) (*Section, error)
	ArchiveSection(ctx context.Context, in *ChangeArchiveRequest, opts ...grpc.CallOption) (*Section, error)
	RestoreSection(ctx context.Context, in *ChangeArchiveRequest, opts ...grpc.CallOption) (*Section, error)
	CreateLesson(ctx context.Context, in *CreateLessonRequest, opts ...grpc.CallOption) (*Lesson, error)
	UpdateLesson(ctx context.Context, in *UpdateLessonRequest, opts ...grpc.CallOption) (*Lesson, error)
	ArchiveLesson(ctx context.Context, in *ChangeArchiveRequest, opts ...grpc.CallOption) (*Lesson, error)
	RestoreLesson(ctx context.Context, in *ChangeArchiveRequest, opts ...grpc.CallOption) (*Lesson, error)
	ChangeLessonStatus(ctx context.Context, in *ChangeLessonStatusRequest, opts ...grpc.CallOption) (*Lesson, error)
	GetMaterialTree(ctx context.Context, in *GetMaterialTreeRequest, opts ...grpc.CallOption) (*MaterialTree, error)
	ReorderMaterial(ctx context.Context, in *ReorderMaterialRequest, opts ...grpc.CallOption) (*MaterialTree, error)
	GetDashboard(ctx context.Context, in *GetDashboardRequest, opts ...grpc.CallOption) (*Dashboard, error)
}

type studyCatalogServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStudyCatalogServiceClient(cc grpc.ClientConnInterface) StudyCatalogServiceClient {
	return &studyCatalogServiceClient{cc}
}

func (c *studyCatalogServiceClient) CreateStudy(ctx context.Context, in *CreateStudyRequest, opts ...grpc.CallOption) (*Study, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Study)
	err := c.cc.Invoke(ctx, StudyCatalogService_CreateStudy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studyCatalogServiceClient) GetStudy(ctx context.Context, in *GetStudyRequest, opts ...grpc.CallOption) (*Study, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Study)
	err := c.cc.Invoke(ctx, StudyCatalogService_GetStudy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studyCatalogServiceClient) ListStudies(ctx context.Context, in *ListStudiesRequest, opts ...grpc.CallOption) (*ListStudiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListStudiesResponse)
	err := c.cc.Invoke(ctx, StudyCatalogService_ListStudies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studyCatalogServiceClient) UpdateStudy(ctx context.Context, in *UpdateStudyRequest, opts ...grpc.CallOption) (*Study, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Study)
	err := c.cc.Invoke(ctx, StudyCatalogService_UpdateStudy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studyCatalogServiceClient) ArchiveStudy(ctx context.Context, in *ChangeArchiveRequest, opts ...grpc.CallOption) (*Study, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Study)
	err := c.cc.Invoke(ctx, StudyCatalogService_ArchiveStudy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studyCatalogServiceClient) RestoreStudy(ctx context.Context, in *ChangeArchiveRequest, opts ...grpc.CallOption) (*Study, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Study)
	err := c.cc.Invoke(ctx, StudyCatalogService_RestoreStudy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studyCatalogServiceClient) CreateLearningSource(ctx context.Context, in *CreateLearningSourceRequest, opts ...grpc.CallOption) (*LearningSource, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LearningSource)
	err := c.cc.Invoke(ctx, StudyCatalogService_CreateLearningSource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studyCatalogServiceClient) UpdateLearningSource(ctx context.Context, in *UpdateLearningSourceRequest, opts ...grpc.CallOption) (*LearningSource, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LearningSource)
	err := c.cc.Invoke(ctx, StudyCatalogService_UpdateLearningSource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studyCatalogServiceClient) ArchiveLearningSource(ctx context.Context, in *ChangeArchiveRequest, opts ...grpc.CallOption) (*LearningSource, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LearningSource)
	err := c.cc.Invoke(ctx, StudyCatalogService_ArchiveLearningSource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studyCatalogServiceClient) RestoreLearningSource(ctx context.Context, in *ChangeArchiveRequest, opts ...grpc.CallOption) (*LearningSource, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LearningSource)
	err := c.cc.Invoke(ctx, StudyCatalogService_RestoreLearningSource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studyCatalogServiceClient) CreateSection(ctx context.Context, in *CreateSectionRequest, opts ...grpc.CallOption) (*Section, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Section)
	err := c.cc.Invoke(ctx, StudyCatalogService_CreateSection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studyCatalogServiceClient) UpdateSection(ctx context.Context, in *UpdateSectionRequest, opts ...grpc.CallOption) (*Section, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Section)
	err := c.cc.Invoke(ctx, StudyCatalogService_UpdateSection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studyCatalogServiceClient) ArchiveSection(ctx context.Context, in *ChangeArchiveRequest, opts ...grpc.CallOption) (*Section, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Section)
	err := c.cc.Invoke(ctx, StudyCatalogService_ArchiveSection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studyCatalogServiceClient) RestoreSection(ctx context.Context, in *ChangeArchiveRequest, opts ...grpc.CallOption) (*Section, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Section)
	err := c.cc.Invoke(ctx, StudyCatalogService_RestoreSection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studyCatalogServiceClient) CreateLesson(ctx context.Context, in *CreateLessonRequest, opts ...grpc.CallOption) (*Lesson, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Lesson)
	err := c.cc.Invoke(ctx, StudyCatalogService_CreateLesson_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studyCatalogServiceClient) UpdateLesson(ctx context.Context, in *UpdateLessonRequest, opts ...grpc.CallOption) (*Lesson, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Lesson)
	err := c.cc.Invoke(ctx, StudyCatalogService_UpdateLesson_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studyCatalogServiceClient) ArchiveLesson(ctx context.Context, in *ChangeArchiveRequest, opts ...grpc.CallOption) (*Lesson, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Lesson)
	err := c.cc.Invoke(ctx, StudyCatalogService_ArchiveLesson_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studyCatalogServiceClient) RestoreLesson(ctx context.Context, in *ChangeArchiveRequest, opts ...grpc.CallOption) (*Lesson, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Lesson)
	err := c.cc.Invoke(ctx, StudyCatalogService_RestoreLesson_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studyCatalogServiceClient) ChangeLessonStatus(ctx context.Context, in *ChangeLessonStatusRequest, opts ...grpc.CallOption) (*Lesson, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Lesson)
	err := c.cc.Invoke(ctx, StudyCatalogService_ChangeLessonStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studyCatalogServiceClient) GetMaterialTree(ctx context.Context, in *GetMaterialTreeRequest, opts ...grpc.CallOption) (*MaterialTree, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MaterialTree)
	err := c.cc.Invoke(ctx, StudyCatalogService_GetMaterialTree_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studyCatalogServiceClient) ReorderMaterial(ctx context.Context, in *ReorderMaterialRequest, opts ...grpc.CallOption) (*MaterialTree, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MaterialTree)
	err := c.cc.Invoke(ctx, StudyCatalogService_ReorderMaterial_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studyCatalogServiceClient) GetDashboard(ctx context.Context, in *GetDashboardRequest, opts ...grpc.CallOption) (*Dashboard, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Dashboard)
	err := c.cc.Invoke(ctx, StudyCatalogService_GetDashboard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StudyCatalogServiceServer is the server API for StudyCatalogService service.
// All implementations must embed UnimplementedStudyCatalogServiceServer
// for forward compatibility.
type StudyCatalogServiceServer interface {
	CreateStudy(context.Context, *CreateStudyRequest) (*Study, error)
	GetStudy(context.Context, *GetStudyRequest) (*Study, error)
	ListStudies(context.Context, *ListStudiesRequest) (*ListStudiesResponse, error)
	UpdateStudy(context.Context, *UpdateStudyRequest) (*Study, error)
	ArchiveStudy(context.Context, *ChangeArchiveRequest) (*Study, error)
	RestoreStudy(context.Context, *ChangeArchiveRequest) (*Study, error)
	CreateLearningSource(context.Context, *CreateLearningSourceRequest) (*LearningSource, error)
	UpdateLearningSource(context.Context, *UpdateLearningSourceRequest) (*LearningSource, error)
	ArchiveLearningSource(context.Context, *ChangeArchiveRequest) (*LearningSource, error)
	RestoreLearningSource(context.Context, *ChangeArchiveRequest) (*LearningSource, error)
	CreateSection(context.Context, *CreateSectionRequest) (*Section, error)
	UpdateSection(context.Context, *UpdateSectionRequest) (*Section, error)
	ArchiveSection(context.Context, *ChangeArchiveRequest) (*Section, error)
	RestoreSection(context.Context, *ChangeArchiveRequest) (*Section, error)
	CreateLesson(context.Context, *CreateLessonRequest) (*Lesson, error)
	UpdateLesson(context.Context, *UpdateLessonRequest) (*Lesson, error)
	ArchiveLesson(context.Context, *ChangeArchiveRequest) (*Lesson, error)
	RestoreLesson(context.Context, *ChangeArchiveRequest) (*Lesson, error)
	ChangeLessonStatus(context.Context, *ChangeLessonStatusRequest) (*Lesson, error)
	GetMaterialTree(context.Context, *GetMaterialTreeRequest) (*MaterialTree, error)
	ReorderMaterial(context.Context, *ReorderMaterialRequest) (*MaterialTree, error)
	GetDashboard(context.Context, *GetDashboardRequest) (*Dashboard, error)
	mustEmbedUnimplementedStudyCatalogServiceServer()
}

// UnimplementedStudyCatalogServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStudyCatalogServiceServer struct{}

func (UnimplementedStudyCatalogServiceServer) CreateStudy(context.Context, *CreateStudyRequest) (*Study, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateStudy not implemented")
}
func (UnimplementedStudyCatalogServiceServer) GetStudy(context.Context, *GetStudyRequest) (*Study, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStudy not implemented")
}
func (UnimplementedStudyCatalogServiceServer) ListStudies(context.Context, *ListStudiesRequest) (*ListStudiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListStudies not implemented")
}
func (UnimplementedStudyCatalogServiceServer) UpdateStudy(context.Context, *UpdateStudyRequest) (*Study, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateStudy not implemented")
}
func (UnimplementedStudyCatalogServiceServer) ArchiveStudy(context.Context, *ChangeArchiveRequest) (*Study, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ArchiveStudy not implemented")
}
func (UnimplementedStudyCatalogServiceServer) RestoreStudy(context.Context, *ChangeArchiveRequest) (*Study, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RestoreStudy not implemented")
}
func (UnimplementedStudyCatalogServiceServer) CreateLearningSource(context.Context, *CreateLearningSourceRequest) (*LearningSource, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLearningSource not implemented")
}
func (UnimplementedStudyCatalogServiceServer) UpdateLearningSource(context.Context, *UpdateLearningSourceRequest) (*LearningSource, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateLearningSource not implemented")
}
func (UnimplementedStudyCatalogServiceServer) ArchiveLearningSource(context.Context, *ChangeArchiveRequest) (*LearningSource, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ArchiveLearningSource not implemented")
}
func (UnimplementedStudyCatalogServiceServer) RestoreLearningSource(context.Context, *ChangeArchiveRequest) (*LearningSource, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RestoreLearningSource not implemented")
}
func (UnimplementedStudyCatalogServiceServer) CreateSection(context.Context, *CreateSectionRequest) (*Section, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSection not implemented")
}
func (UnimplementedStudyCatalogServiceServer) UpdateSection(context.Context, *UpdateSectionRequest) (*Section, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSection not implemented")
}
func (UnimplementedStudyCatalogServiceServer) ArchiveSection(context.Context, *ChangeArchiveRequest) (*Section, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ArchiveSection not implemented")
}
func (UnimplementedStudyCatalogServiceServer) RestoreSection(context.Context, *ChangeArchiveRequest) (*Section, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RestoreSection not implemented")
}
func (UnimplementedStudyCatalogServiceServer) CreateLesson(context.Context, *CreateLessonRequest) (*Lesson, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLesson not implemented")
}
func (UnimplementedStudyCatalogServiceServer) UpdateLesson(context.Context, *UpdateLessonRequest) (*Lesson, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateLesson not implemented")
}
func (UnimplementedStudyCatalogServiceServer) ArchiveLesson(context.Context, *ChangeArchiveRequest) (*Lesson, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ArchiveLesson not implemented")
}
func (UnimplementedStudyCatalogServiceServer) RestoreLesson(context.Context, *ChangeArchiveRequest) (*Lesson, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RestoreLesson not implemented")
}
func (UnimplementedStudyCatalogServiceServer) ChangeLessonStatus(context.Context, *ChangeLessonStatusRequest) (*Lesson, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeLessonStatus not implemented")
}
func (UnimplementedStudyCatalogServiceServer) GetMaterialTree(context.Context, *GetMaterialTreeRequest) (*MaterialTree, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMaterialTree not implemented")
}
func (UnimplementedStudyCatalogServiceServer) ReorderMaterial(context.Context, *ReorderMaterialRequest) (*MaterialTree, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReorderMaterial not implemented")
}
func (UnimplementedStudyCatalogServiceServer) GetDashboard(context.Context, *GetDashboardRequest) (*Dashboard, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDashboard not implemented")
}
func (UnimplementedStudyCatalogServiceServer) mustEmbedUnimplementedStudyCatalogServiceServer() {}
func (UnimplementedStudyCatalogServiceServer) testEmbeddedByValue()                             {}

// UnsafeStudyCatalogServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StudyCatalogServiceServer will
// result in compilation errors.
type UnsafeStudyCatalogServiceServer interface {
	mustEmbedUnimplementedStudyCatalogServiceServer()
}

func RegisterStudyCatalogServiceServer(s grpc.ServiceRegistrar, srv StudyCatalogServiceServer) {
	// If the following call pancis, it indicates UnimplementedStudyCatalogServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StudyCatalogService_ServiceDesc, srv)
}

func _StudyCatalogService_CreateStudy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateStudyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudyCatalogServiceServer).CreateStudy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StudyCatalogService_CreateStudy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudyCatalogServiceServer).CreateStudy(ctx, req.(*CreateStudyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudyCatalogService_GetStudy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStudyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudyCatalogServiceServer).GetStudy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StudyCatalogService_GetStudy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudyCatalogServiceServer).GetStudy(ctx, req.(*GetStudyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudyCatalogService_ListStudies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListStudiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudyCatalogServiceServer).ListStudies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StudyCatalogService_ListStudies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudyCatalogServiceServer).ListStudies(ctx, req.(*ListStudiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudyCatalogService_UpdateStudy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStudyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudyCatalogServiceServer).UpdateStudy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StudyCatalogService_UpdateStudy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudyCatalogServiceServer).UpdateStudy(ctx, req.(*UpdateStudyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudyCatalogService_ArchiveStudy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeArchiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudyCatalogServiceServer).ArchiveStudy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StudyCatalogService_ArchiveStudy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudyCatalogServiceServer).ArchiveStudy(ctx, req.(*ChangeArchiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudyCatalogService_RestoreStudy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeArchiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudyCatalogServiceServer).RestoreStudy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StudyCatalogService_RestoreStudy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudyCatalogServiceServer).RestoreStudy(ctx, req.(*ChangeArchiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudyCatalogService_CreateLearningSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLearningSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudyCatalogServiceServer).CreateLearningSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StudyCatalogService_CreateLearningSource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudyCatalogServiceServer).CreateLearningSource(ctx, req.(*CreateLearningSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudyCatalogService_UpdateLearningSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateLearningSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudyCatalogServiceServer).UpdateLearningSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StudyCatalogService_UpdateLearningSource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudyCatalogServiceServer).UpdateLearningSource(ctx, req.(*UpdateLearningSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudyCatalogService_ArchiveLearningSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeArchiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudyCatalogServiceServer).ArchiveLearningSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StudyCatalogService_ArchiveLearningSource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudyCatalogServiceServer).ArchiveLearningSource(ctx, req.(*ChangeArchiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudyCatalogService_RestoreLearningSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeArchiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudyCatalogServiceServer).RestoreLearningSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StudyCatalogService_RestoreLearningSource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudyCatalogServiceServer).RestoreLearningSource(ctx, req.(*ChangeArchiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudyCatalogService_CreateSection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudyCatalogServiceServer).CreateSection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StudyCatalogService_CreateSection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudyCatalogServiceServer).CreateSection(ctx, req.(*CreateSectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudyCatalogService_UpdateSection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudyCatalogServiceServer).UpdateSection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StudyCatalogService_UpdateSection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudyCatalogServiceServer).UpdateSection(ctx, req.(*UpdateSectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudyCatalogService_ArchiveSection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeArchiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudyCatalogServiceServer).ArchiveSection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StudyCatalogService_ArchiveSection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudyCatalogServiceServer).ArchiveSection(ctx, req.(*ChangeArchiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudyCatalogService_RestoreSection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeArchiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudyCatalogServiceServer).RestoreSection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StudyCatalogService_RestoreSection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudyCatalogServiceServer).RestoreSection(ctx, req.(*ChangeArchiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudyCatalogService_CreateLesson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLessonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudyCatalogServiceServer).CreateLesson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StudyCatalogService_CreateLesson_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudyCatalogServiceServer).CreateLesson(ctx, req.(*CreateLessonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudyCatalogService_UpdateLesson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateLessonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudyCatalogServiceServer).UpdateLesson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StudyCatalogService_UpdateLesson_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudyCatalogServiceServer).UpdateLesson(ctx, req.(*UpdateLessonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudyCatalogService_ArchiveLesson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeArchiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudyCatalogServiceServer).ArchiveLesson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StudyCatalogService_ArchiveLesson_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudyCatalogServiceServer).ArchiveLesson(ctx, req.(*ChangeArchiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudyCatalogService_RestoreLesson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeArchiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudyCatalogServiceServer).RestoreLesson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StudyCatalogService_RestoreLesson_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudyCatalogServiceServer).RestoreLesson(ctx, req.(*ChangeArchiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudyCatalogService_ChangeLessonStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeLessonStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudyCatalogServiceServer).ChangeLessonStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StudyCatalogService_ChangeLessonStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudyCatalogServiceServer).ChangeLessonStatus(ctx, req.(*ChangeLessonStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudyCatalogService_GetMaterialTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMaterialTreeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudyCatalogServiceServer).GetMaterialTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StudyCatalogService_GetMaterialTree_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudyCatalogServiceServer).GetMaterialTree(ctx, req.(*GetMaterialTreeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudyCatalogService_ReorderMaterial_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReorderMaterialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudyCatalogServiceServer).ReorderMaterial(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StudyCatalogService_ReorderMaterial_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudyCatalogServiceServer).ReorderMaterial(ctx, req.(*ReorderMaterialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudyCatalogService_GetDashboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDashboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudyCatalogServiceServer).GetDashboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StudyCatalogService_GetDashboard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudyCatalogServiceServer).GetDashboard(ctx, req.(*GetDashboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StudyCatalogService_ServiceDesc is the grpc.ServiceDesc for StudyCatalogService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StudyCatalogService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wantstudy.v1.StudyCatalogService",
	HandlerType: (*StudyCatalogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateStudy",
			Handler:    _StudyCatalogService_CreateStudy_Handler,
		},
		{
			MethodName: "GetStudy",
			Handler:    _StudyCatalogService_GetStudy_Handler,
		},
		{
			MethodName: "ListStudies",
			Handler:    _StudyCatalogService_ListStudies_Handler,
		},
		{
			MethodName: "UpdateStudy",
			Handler:    _StudyCatalogService_UpdateStudy_Handler,
		},
		{
			MethodName: "ArchiveStudy",
			Handler:    _StudyCatalogService_ArchiveStudy_Handler,
		},
		{
			MethodName: "RestoreStudy",
			Handler:    _StudyCatalogService_RestoreStudy_Handler,
		},
		{
			MethodName: "CreateLearningSource",
			Handler:    _StudyCatalogService_CreateLearningSource_Handler,
		},
		{
			MethodName: "UpdateLearningSource",
			Handler:    _StudyCatalogService_UpdateLearningSource_Handler,
		},
		{
			MethodName: "ArchiveLearningSource",
			Handler:    _StudyCatalogService_ArchiveLearningSource_Handler,
		},
		{
			MethodName: "RestoreLearningSource",
			Handler:    _StudyCatalogService_RestoreLearningSource_Handler,
		},
		{
			MethodName: "CreateSection",
			Handler:    _StudyCatalogService_CreateSection_Handler,
		},
		{
			MethodName: "UpdateSection",
			Handler:    _StudyCatalogService_UpdateSection_Handler,
		},
		{
			MethodName: "ArchiveSection",
			Handler:    _StudyCatalogService_ArchiveSection_Handler,
		},
		{
			MethodName: "RestoreSection",
			Handler:    _StudyCatalogService_RestoreSection_Handler,
		},
		{
			MethodName: "CreateLesson",
			Handler:    _StudyCatalogService_CreateLesson_Handler,
		},
		{
			MethodName: "UpdateLesson",
			Handler:    _StudyCatalogService_UpdateLesson_Handler,
		},
		{
			MethodName: "ArchiveLesson",
			Handler:    _StudyCatalogService_ArchiveLesson_Handler,
		},
		{
			MethodName: "RestoreLesson",
			Handler:    _StudyCatalogService_RestoreLesson_Handler,
		},
		{
			MethodName: "ChangeLessonStatus",
			Handler:    _StudyCatalogService_ChangeLessonStatus_Handler,
		},
		{
			MethodName: "GetMaterialTree",
			Handler:    _StudyCatalogService_GetMaterialTree_Handler,
		},
		{
			MethodName: "ReorderMaterial",
			Handler:    _StudyCatalogService_ReorderMaterial_Handler,
		},
		{
			MethodName: "GetDashboard",
			Handler:    _StudyCatalogService_GetDashboard_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wantstudy/v1/study.proto",
}
