// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: wantstudy/v1/study.proto

package wantstudyv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LearningSourceType int32

const (
	LearningSourceType_LEARNING_SOURCE_TYPE_UNSPECIFIED LearningSourceType = 0
	LearningSourceType_LEARNING_SOURCE_TYPE_COURSE      LearningSourceType = 1
	LearningSourceType_LEARNING_SOURCE_TYPE_BOOK        LearningSourceType = 2
	LearningSourceType_LEARNING_SOURCE_TYPE_ARTICLE     LearningSourceType = 3
	LearningSourceType_LEARNING_SOURCE_TYPE_VIDEO       LearningSourceType = 4
	LearningSourceType_LEARNING_SOURCE_TYPE_OTHER       LearningSourceType = 5
)

// Enum value maps for LearningSourceType.
var (
	LearningSourceType_name = map[int32]string{
		0: "LEARNING_SOURCE_TYPE_UNSPECIFIED",
		1: "LEARNING_SOURCE_TYPE_COURSE",
		2: "LEARNING_SOURCE_TYPE_BOOK",
		3: "LEARNING_SOURCE_TYPE_ARTICLE",
		4: "LEARNING_SOURCE_TYPE_VIDEO",
		5: "LEARNING_SOURCE_TYPE_OTHER",
	}
	LearningSourceType_value = map[string]int32{
		"LEARNING_SOURCE_TYPE_UNSPECIFIED": 0,
		"LEARNING_SOURCE_TYPE_COURSE":      1,
		"LEARNING_SOURCE_TYPE_BOOK":        2,
		"LEARNING_SOURCE_TYPE_ARTICLE":     3,
		"LEARNING_SOURCE_TYPE_VIDEO":       4,
		"LEARNING_SOURCE_TYPE_OTHER":       5,
	}
)

func (x LearningSourceType) Enum() *LearningSourceType {
	p := new(LearningSourceType)
	*p = x
	return p
}

func (x LearningSourceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LearningSourceType) Descriptor() protoreflect.EnumDescriptor {
	return file_wantstudy_v1_study_proto_enumTypes[0].Descriptor()
}

func (LearningSourceType) Type() protoreflect.EnumType {
	return &file_wantstudy_v1_study_proto_enumTypes[0]
}

func (x LearningSourceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LearningSourceType.Descriptor instead.
func (LearningSourceType) EnumDescriptor() ([]byte, []int) {
	return file_wantstudy_v1_study_proto_rawDescGZIP(), []int{0}
}

type LessonStatus int32

const (
	LessonStatus_LESSON_STATUS_UNSPECIFIED LessonStatus = 0
	LessonStatus_LESSON_STATUS_PLANNED     LessonStatus = 1
	LessonStatus_LESSON_STATUS_STUDYING    LessonStatus = 2
	LessonStatus_LESSON_STATUS_HOMEWORK    LessonStatus = 3
	LessonStatus_LESSON_STATUS_MASTERED    LessonStatus = 4
)

// Enum value maps for LessonStatus.
var (
	LessonStatus_name = map[int32]string{
		0: "LESSON_STATUS_UNSPECIFIED",
		1: "LESSON_STATUS_PLANNED",
		2: "LESSON_STATUS_STUDYING",
		3: "LESSON_STATUS_HOMEWORK",
		4: "LESSON_STATUS_MASTERED",
	}
	LessonStatus_value = map[string]int32{
		"LESSON_STATUS_UNSPECIFIED": 0,
		"LESSON_STATUS_PLANNED":     1,
		"LESSON_STATUS_STUDYING":    2,
		"LESSON_STATUS_HOMEWORK":    3,
		"LESSON_STATUS_MASTERED":    4,
	}
)

func (x LessonStatus) Enum() *LessonStatus {
	p := new(LessonStatus)
	*p = x
	return p
}

func (x LessonStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LessonStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_wantstudy_v1_study_proto_enumTypes[1].Descriptor()
}

func (LessonStatus) Type() protoreflect.EnumType {
	return &file_wantstudy_v1_study_proto_enumTypes[1]
}

func (x LessonStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LessonStatus.Descriptor instead.
func (LessonStatus) EnumDescriptor() ([]byte, []int) {
	return file_wantstudy_v1_study_proto_rawDescGZIP(), []int{1}
}

type Study struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Goal                 string                 `protobuf:"bytes,3,opt,name=goal,proto3" json:"goal,omitempty"`
	LocalRepositoryPath  string                 `protobuf:"bytes,4,opt,name=local_repository_path,json=localRepositoryPath,proto3" json:"local_repository_path,omitempty"`
	Version              int64                  `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	ContentRevision      int64                  `protobuf:"varint,6,opt,name=content_revision,json=contentRevision,proto3" json:"content_revision,omitempty"`
	Archived             bool                   `protobuf:"varint,7,opt,name=archived,proto3" json:"archived,omitempty"`
	CreatedAtEpochMillis int64                  `protobuf:"varint,8,opt,name=created_at_epoch_millis,json=createdAtEpochMillis,proto3" json:"created_at_epoch_millis,omitempty"`
	UpdatedAtEpochMillis int64                  `protobuf:"varint,9,opt,name=updated_at_epoch_millis,json=updatedAtEpochMillis,proto3" json:"updated_at_epoch_millis,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Study) Reset() {
	*x = Study{}
	mi := &file_wantstudy_v1_study_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Study) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Study) ProtoMessage() {}

func (x *Study) ProtoReflect() protoreflect.Message {
	mi := &file_wantstudy_v1_study_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Study.ProtoReflect.Descriptor instead.
func (*Study) Descriptor() ([]byte, []int) {
	return file_wantstudy_v1_study_proto_rawDescGZIP(), []int{0}
}

func (x *Study) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Study) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Study) GetGoal() string {
	if x != nil {
		return x.Goal
	}
	return ""
}

func (x *Study) GetLocalRepositoryPath() string {
	if x != nil {
		return x.LocalRepositoryPath
	}
	return ""
}

func (x *Study) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Study) GetContentRevision() int64 {
	if x != nil {
		return x.ContentRevision
	}
	return 0
}

func (x *Study) GetArchived() bool {
	if x != nil {
		return x.Archived
	}
	return false
}

func (x *Study) GetCreatedAtEpochMillis() int64 {
	if x != nil {
		return x.CreatedAtEpochMillis
	}
	return 0
}

func (x *Study) GetUpdatedAtEpochMillis() int64 {
	if x != nil {
		return x.UpdatedAtEpochMillis
	}
	return 0
}

type LearningSource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StudyId       string                 `protobuf:"bytes,2,opt,name=study_id,json=studyId,proto3" json:"study_id,omitempty"`
	Type          LearningSourceType     `protobuf:"varint,3,opt,name=type,proto3,enum=wantstudy.v1.LearningSourceType" json:"type,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Author        string                 `protobuf:"bytes,5,opt,name=author,proto3" json:"author,omitempty"`
	Url           string                 `protobuf:"bytes,6,opt,name=url,proto3" json:"url,omitempty"`
	ExportSlug    string                 `protobuf:"bytes,7,opt,name=export_slug,json=exportSlug,proto3" json:"export_slug,omitempty"`
	Position      int32                  `protobuf:"varint,8,opt,name=position,proto3" json:"position,omitempty"`
	Version       int64                  `protobuf:"varint,9,opt,name=version,proto3" json:"version,omitempty"`
	Archived      bool                   `protobuf:"varint,10,opt,name=archived,proto3" json:"archived,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LearningSource) Reset() {
	*x = LearningSource{}
	mi := &file_wantstudy_v1_study_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LearningSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LearningSource) ProtoMessage() {}

func (x *LearningSource) ProtoReflect() protoreflect.Message {
	mi := &file_wantstudy_v1_study_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LearningSource.ProtoReflect.Descriptor instead.
func (*LearningSource) Descriptor() ([]byte, []int) {
	return file_wantstudy_v1_study_proto_rawDescGZIP(), []int{1}
}

func (x *LearningSource) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LearningSource) GetStudyId() string {
	if x != nil {
		return x.StudyId
	}
	return ""
}

func (x *LearningSource) GetType() LearningSourceType {
	if x != nil {
		return x.Type
	}
	return LearningSourceType_LEARNING_SOURCE_TYPE_UNSPECIFIED
}

func (x *LearningSource) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *LearningSource) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *LearningSource) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *LearningSource) GetExportSlug() string {
	if x != nil {
		return x.ExportSlug
	}
	return ""
}

func (x *LearningSource) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *LearningSource) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *LearningSource) GetArchived() bool {
	if x != nil {
		return x.Archived
	}
	return false
}

type Section struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StudyId       string                 `protobuf:"bytes,2,opt,name=study_id,json=studyId,proto3" json:"study_id,omitempty"`
	SourceId      string                 `protobuf:"bytes,3,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Position      int32                  `protobuf:"varint,5,opt,name=position,proto3" json:"position,omitempty"`
	Version       int64                  `protobuf:"varint,6,opt,name=version,proto3" json:"version,omitempty"`
	Archived      bool                   `protobuf:"varint,7,opt,name=archived,proto3" json:"archived,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Section) Reset() {
	*x = Section{}
	mi := &file_wantstudy_v1_study_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Section) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Section) ProtoMessage() {}

func (x *Section) ProtoReflect() protoreflect.Message {
	mi := &file_wantstudy_v1_study_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Section.ProtoReflect.Descriptor instead.
func (*Section) Descriptor() ([]byte, []int) {
	return file_wantstudy_v1_study_proto_rawDescGZIP(), []int{2}
}

func (x *Section) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Section) GetStudyId() string {
	if x != nil {
		return x.StudyId
	}
	return ""
}

func (x *Section) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *Section) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Section) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *Section) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Section) GetArchived() bool {
	if x != nil {
		return x.Archived
	}
	return false
}

type Lesson struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StudyId               string                 `protobuf:"bytes,2,opt,name=study_id,json=studyId,proto3" json:"study_id,omitempty"`
	SourceId              string                 `protobuf:"bytes,3,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	SectionId             *string                `protobuf:"bytes,4,opt,name=section_id,json=sectionId,proto3,oneof" json:"section_id,omitempty"`
	Title                 string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Url                   string                 `protobuf:"bytes,6,opt,name=url,proto3" json:"url,omitempty"`
	SourcePosition        string                 `protobuf:"bytes,7,opt,name=source_position,json=sourcePosition,proto3" json:"source_position,omitempty"`
	ExportSlug            string                 `protobuf:"bytes,8,opt,name=export_slug,json=exportSlug,proto3" json:"export_slug,omitempty"`
	Position              int32                  `protobuf:"varint,9,opt,name=position,proto3" json:"position,omitempty"`
	Status                LessonStatus           `protobuf:"varint,10,opt,name=status,proto3,enum=wantstudy.v1.LessonStatus" json:"status,omitempty"`
	StartedAtEpochMillis  *int64                 `protobuf:"varint,11,opt,name=started_at_epoch_millis,json=startedAtEpochMillis,proto3,oneof" json:"started_at_epoch_millis,omitempty"`
	MasteredAtEpochMillis *int64                 `protobuf:"varint,12,opt,name=mastered_at_epoch_millis,json=masteredAtEpochMillis,proto3,oneof" json:"mastered_at_epoch_millis,omitempty"`
	Version               int64                  `protobuf:"varint,13,opt,name=version,proto3" json:"version,omitempty"`
	Archived              bool                   `protobuf:"varint,14,opt,name=archived,proto3" json:"archived,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Lesson) Reset() {
	*x = Lesson{}
	mi := &file_wantstudy_v1_study_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lesson) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lesson) ProtoMessage() {}

func (x *Lesson) ProtoReflect() protoreflect.Message {
	mi := &file_wantstudy_v1_study_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lesson.ProtoReflect.Descriptor instead.
func (*Lesson) Descriptor() ([]byte, []int) {
	return file_wantstudy_v1_study_proto_rawDescGZIP(), []int{3}
}

func (x *Lesson) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Lesson) GetStudyId() string {
	if x != nil {
		return x.StudyId
	}
	return ""
}

func (x *Lesson) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *Lesson) GetSectionId() string {
	if x != nil && x.SectionId != nil {
		return *x.SectionId
	}
	return ""
}

func (x *Lesson) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Lesson) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Lesson) GetSourcePosition() string {
	if x != nil {
		return x.SourcePosition
	}
	return ""
}

func (x *Lesson) GetExportSlug() string {
	if x != nil {
		return x.ExportSlug
	}
	return ""
}

func (x *Lesson) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *Lesson) GetStatus() LessonStatus {
	if x != nil {
		return x.Status
	}
	return LessonStatus_LESSON_STATUS_UNSPECIFIED
}

func (x *Lesson) GetStartedAtEpochMillis() int64 {
	if x != nil && x.StartedAtEpochMillis != nil {
		return *x.StartedAtEpochMillis
	}
	return 0
}

func (x *Lesson) GetMasteredAtEpochMillis() int64 {
	if x != nil && x.MasteredAtEpochMillis != nil {
		return *x.MasteredAtEpochMillis
	}
	return 0
}

func (x *Lesson) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Lesson) GetArchived() bool {
	if x != nil {
		return x.Archived
	}
	return false
}

type CreateStudyRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title               string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Goal                string                 `protobuf:"bytes,3,opt,name=goal,proto3" json:"goal,omitempty"`
	LocalRepositoryPath string                 `protobuf:"bytes,4,opt,name=local_repository_path,json=localRepositoryPath,proto3" json:"local_repository_path,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CreateStudyRequest) Reset() {
	*x = CreateStudyRequest{}
	mi := &file_wantstudy_v1_study_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStudyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStudyRequest) ProtoMessage() {}

func (x *CreateStudyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wantstudy_v1_study_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStudyRequest.ProtoReflect.Descriptor instead.
func (*CreateStudyRequest) Descriptor() ([]byte, []int) {
	return file_wantstudy_v1_study_proto_rawDescGZIP(), []int{4}
}

func (x *CreateStudyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateStudyRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateStudyRequest) GetGoal() string {
	if x != nil {
		return x.Goal
	}
	return ""
}

func (x *CreateStudyRequest) GetLocalRepositoryPath() string {
	if x != nil {
		return x.LocalRepositoryPath
	}
	return ""
}

type GetStudyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStudyRequest) Reset() {
	*x = GetStudyRequest{}
	mi := &file_wantstudy_v1_study_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStudyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStudyRequest) ProtoMessage() {}

func (x *GetStudyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wantstudy_v1_study_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStudyRequest.ProtoReflect.Descriptor instead.
func (*GetStudyRequest) Descriptor() ([]byte, []int) {
	return file_wantstudy_v1_study_proto_rawDescGZIP(), []int{5}
}

func (x *GetStudyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListStudiesRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	IncludeArchived bool                   `protobuf:"varint,1,opt,name=include_archived,json=includeArchived,proto3" json:"include_archived,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListStudiesRequest) Reset() {
	*x = ListStudiesRequest{}
	mi := &file_wantstudy_v1_study_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStudiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStudiesRequest) ProtoMessage() {}

func (x *ListStudiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wantstudy_v1_study_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStudiesRequest.ProtoReflect.Descriptor instead.
func (*ListStudiesRequest) Descriptor() ([]byte, []int) {
	return file_wantstudy_v1_study_proto_rawDescGZIP(), []int{6}
}

func (x *ListStudiesRequest) GetIncludeArchived() bool {
	if x != nil {
		return x.IncludeArchived
	}
	return false
}

type ListStudiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Studies       []*Study               `protobuf:"bytes,1,rep,name=studies,proto3" json:"studies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStudiesResponse) Reset() {
	*x = ListStudiesResponse{}
	mi := &file_wantstudy_v1_study_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStudiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStudiesResponse) ProtoMessage() {}

func (x *ListStudiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wantstudy_v1_study_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStudiesResponse.ProtoReflect.Descriptor instead.
func (*ListStudiesResponse) Descriptor() ([]byte, []int) {
	return file_wantstudy_v1_study_proto_rawDescGZIP(), []int{7}
}

func (x *ListStudiesResponse) GetStudies() []*Study {
	if x != nil {
		return x.Studies
	}
	return nil
}

type UpdateStudyRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title               string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Goal                string                 `protobuf:"bytes,3,opt,name=goal,proto3" json:"goal,omitempty"`
	LocalRepositoryPath string                 `protobuf:"bytes,4,opt,name=local_repository_path,json=localRepositoryPath,proto3" json:"local_repository_path,omitempty"`
	ExpectedVersion     int64                  `protobuf:"varint,5,opt,name=expected_version,json=expectedVersion,proto3" json:"expected_version,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *UpdateStudyRequest) Reset() {
	*x = UpdateStudyRequest{}
	mi := &file_wantstudy_v1_study_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStudyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStudyRequest) ProtoMessage() {}

func (x *UpdateStudyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wantstudy_v1_study_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStudyRequest.ProtoReflect.Descriptor instead.
func (*UpdateStudyRequest) Descriptor() ([]byte, []int) {
	return file_wantstudy_v1_study_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateStudyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateStudyRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateStudyRequest) GetGoal() string {
	if x != nil {
		return x.Goal
	}
	return ""
}

func (x *UpdateStudyRequest) GetLocalRepositoryPath() string {
	if x != nil {
		return x.LocalRepositoryPath
	}
	return ""
}

func (x *UpdateStudyRequest) GetExpectedVersion() int64 {
	if x != nil {
		return x.ExpectedVersion
	}
	return 0
}

type ChangeArchiveRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ExpectedVersion int64                  `protobuf:"varint,2,opt,name=expected_version,json=expectedVersion,proto3" json:"expected_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ChangeArchiveRequest) Reset() {
	*x = ChangeArchiveRequest{}
	mi := &file_wantstudy_v1_study_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeArchiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeArchiveRequest) ProtoMessage() {}

func (x *ChangeArchiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wantstudy_v1_study_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeArchiveRequest.ProtoReflect.Descriptor instead.
func (*ChangeArchiveRequest) Descriptor() ([]byte, []int) {
	return file_wantstudy_v1_study_proto_rawDescGZIP(), []int{9}
}

func (x *ChangeArchiveRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChangeArchiveRequest) GetExpectedVersion() int64 {
	if x != nil {
		return x.ExpectedVersion
	}
	return 0
}

type CreateLearningSourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StudyId       string                 `protobuf:"bytes,2,opt,name=study_id,json=studyId,proto3" json:"study_id,omitempty"`
	Type          LearningSourceType     `protobuf:"varint,3,opt,name=type,proto3,enum=wantstudy.v1.LearningSourceType" json:"type,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Author        string                 `protobuf:"bytes,5,opt,name=author,proto3" json:"author,omitempty"`
	Url           string                 `protobuf:"bytes,6,opt,name=url,proto3" json:"url,omitempty"`
	ExportSlug    string                 `protobuf:"bytes,7,opt,name=export_slug,json=exportSlug,proto3" json:"export_slug,omitempty"`
	Position      int32                  `protobuf:"varint,8,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLearningSourceRequest) Reset() {
	*x = CreateLearningSourceRequest{}
	mi := &file_wantstudy_v1_study_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLearningSourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLearningSourceRequest) ProtoMessage() {}

func (x *CreateLearningSourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wantstudy_v1_study_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLearningSourceRequest.ProtoReflect.Descriptor instead.
func (*CreateLearningSourceRequest) Descriptor() ([]byte, []int) {
	return file_wantstudy_v1_study_proto_rawDescGZIP(), []int{10}
}

func (x *CreateLearningSourceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateLearningSourceRequest) GetStudyId() string {
	if x != nil {
		return x.StudyId
	}
	return ""
}

func (x *CreateLearningSourceRequest) GetType() LearningSourceType {
	if x != nil {
		return x.Type
	}
	return LearningSourceType_LEARNING_SOURCE_TYPE_UNSPECIFIED
}

func (x *CreateLearningSourceRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateLearningSourceRequest) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *CreateLearningSourceRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CreateLearningSourceRequest) GetExportSlug() string {
	if x != nil {
		return x.ExportSlug
	}
	return ""
}

func (x *CreateLearningSourceRequest) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

type UpdateLearningSourceRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Source          *LearningSource        `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	ExpectedVersion int64                  `protobuf:"varint,2,opt,name=expected_version,json=expectedVersion,proto3" json:"expected_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateLearningSourceRequest) Reset() {
	*x = UpdateLearningSourceRequest{}
	mi := &file_wantstudy_v1_study_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLearningSourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLearningSourceRequest) ProtoMessage() {}

func (x *UpdateLearningSourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wantstudy_v1_study_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLearningSourceRequest.ProtoReflect.Descriptor instead.
func (*UpdateLearningSourceRequest) Descriptor() ([]byte, []int) {
	return file_wantstudy_v1_study_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateLearningSourceRequest) GetSource() *LearningSource {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *UpdateLearningSourceRequest) GetExpectedVersion() int64 {
	if x != nil {
		return x.ExpectedVersion
	}
	return 0
}

type CreateSectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StudyId       string                 `protobuf:"bytes,2,opt,name=study_id,json=studyId,proto3" json:"study_id,omitempty"`
	SourceId      string                 `protobuf:"bytes,3,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Position      int32                  `protobuf:"varint,5,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSectionRequest) Reset() {
	*x = CreateSectionRequest{}
	mi := &file_wantstudy_v1_study_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSectionRequest) ProtoMessage() {}

func (x *CreateSectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wantstudy_v1_study_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSectionRequest.ProtoReflect.Descriptor instead.
func (*CreateSectionRequest) Descriptor() ([]byte, []int) {
	return file_wantstudy_v1_study_proto_rawDescGZIP(), []int{12}
}

func (x *CreateSectionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateSectionRequest) GetStudyId() string {
	if x != nil {
		return x.StudyId
	}
	return ""
}

func (x *CreateSectionRequest) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *CreateSectionRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateSectionRequest) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

type UpdateSectionRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Section         *Section               `protobuf:"bytes,1,opt,name=section,proto3" json:"section,omitempty"`
	ExpectedVersion int64                  `protobuf:"varint,2,opt,name=expected_version,json=expectedVersion,proto3" json:"expected_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateSectionRequest) Reset() {
	*x = UpdateSectionRequest{}
	mi := &file_wantstudy_v1_study_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSectionRequest) ProtoMessage() {}

func (x *UpdateSectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wantstudy_v1_study_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSectionRequest.ProtoReflect.Descriptor instead.
func (*UpdateSectionRequest) Descriptor() ([]byte, []int) {
	return file_wantstudy_v1_study_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateSectionRequest) GetSection() *Section {
	if x != nil {
		return x.Section
	}
	return nil
}

func (x *UpdateSectionRequest) GetExpectedVersion() int64 {
	if x != nil {
		return x.ExpectedVersion
	}
	return 0
}

type CreateLessonRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StudyId        string                 `protobuf:"bytes,2,opt,name=study_id,json=studyId,proto3" json:"study_id,omitempty"`
	SourceId       string                 `protobuf:"bytes,3,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	SectionId      *string                `protobuf:"bytes,4,opt,name=section_id,json=sectionId,proto3,oneof" json:"section_id,omitempty"`
	Title          string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Url            string                 `protobuf:"bytes,6,opt,name=url,proto3" json:"url,omitempty"`
	SourcePosition string                 `protobuf:"bytes,7,opt,name=source_position,json=sourcePosition,proto3" json:"source_position,omitempty"`
	ExportSlug     string                 `protobuf:"bytes,8,opt,name=export_slug,json=exportSlug,proto3" json:"export_slug,omitempty"`
	Position       int32                  `protobuf:"varint,9,opt,name=position,proto3" json:"position,omitempty"`
	Status         LessonStatus           `protobuf:"varint,10,opt,name=status,proto3,enum=wantstudy.v1.LessonStatus" json:"status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateLessonRequest) Reset() {
	*x = CreateLessonRequest{}
	mi := &file_wantstudy_v1_study_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLessonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLessonRequest) ProtoMessage() {}

func (x *CreateLessonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wantstudy_v1_study_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLessonRequest.ProtoReflect.Descriptor instead.
func (*CreateLessonRequest) Descriptor() ([]byte, []int) {
	return file_wantstudy_v1_study_proto_rawDescGZIP(), []int{14}
}

func (x *CreateLessonRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateLessonRequest) GetStudyId() string {
	if x != nil {
		return x.StudyId
	}
	return ""
}

func (x *CreateLessonRequest) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *CreateLessonRequest) GetSectionId() string {
	if x != nil && x.SectionId != nil {
		return *x.SectionId
	}
	return ""
}

func (x *CreateLessonRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateLessonRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CreateLessonRequest) GetSourcePosition() string {
	if x != nil {
		return x.SourcePosition
	}
	return ""
}

func (x *CreateLessonRequest) GetExportSlug() string {
	if x != nil {
		return x.ExportSlug
	}
	return ""
}

func (x *CreateLessonRequest) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *CreateLessonRequest) GetStatus() LessonStatus {
	if x != nil {
		return x.Status
	}
	return LessonStatus_LESSON_STATUS_UNSPECIFIED
}

type UpdateLessonRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Lesson          *Lesson                `protobuf:"bytes,1,opt,name=lesson,proto3" json:"lesson,omitempty"`
	ExpectedVersion int64                  `protobuf:"varint,2,opt,name=expected_version,json=expectedVersion,proto3" json:"expected_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateLessonRequest) Reset() {
	*x = UpdateLessonRequest{}
	mi := &file_wantstudy_v1_study_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLessonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLessonRequest) ProtoMessage() {}

func (x *UpdateLessonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wantstudy_v1_study_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLessonRequest.ProtoReflect.Descriptor instead.
func (*UpdateLessonRequest) Descriptor() ([]byte, []int) {
	return file_wantstudy_v1_study_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateLessonRequest) GetLesson() *Lesson {
	if x != nil {
		return x.Lesson
	}
	return nil
}

func (x *UpdateLessonRequest) GetExpectedVersion() int64 {
	if x != nil {
		return x.ExpectedVersion
	}
	return 0
}

type ChangeLessonStatusRequest struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Id                      string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status                  LessonStatus           `protobuf:"varint,2,opt,name=status,proto3,enum=wantstudy.v1.LessonStatus" json:"status,omitempty"`
	ExpectedVersion         int64                  `protobuf:"varint,3,opt,name=expected_version,json=expectedVersion,proto3" json:"expected_version,omitempty"`
	AcknowledgeOpenHomework bool                   `protobuf:"varint,4,opt,name=acknowledge_open_homework,json=acknowledgeOpenHomework,proto3" json:"acknowledge_open_homework,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ChangeLessonStatusRequest) Reset() {
	*x = ChangeLessonStatusRequest{}
	mi := &file_wantstudy_v1_study_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeLessonStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeLessonStatusRequest) ProtoMessage() {}

func (x *ChangeLessonStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wantstudy_v1_study_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeLessonStatusRequest.ProtoReflect.Descriptor instead.
func (*ChangeLessonStatusRequest) Descriptor() ([]byte, []int) {
	return file_wantstudy_v1_study_proto_rawDescGZIP(), []int{16}
}

func (x *ChangeLessonStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChangeLessonStatusRequest) GetStatus() LessonStatus {
	if x != nil {
		return x.Status
	}
	return LessonStatus_LESSON_STATUS_UNSPECIFIED
}

func (x *ChangeLessonStatusRequest) GetExpectedVersion() int64 {
	if x != nil {
		return x.ExpectedVersion
	}
	return 0
}

func (x *ChangeLessonStatusRequest) GetAcknowledgeOpenHomework() bool {
	if x != nil {
		return x.AcknowledgeOpenHomework
	}
	return false
}

type GetMaterialTreeRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	StudyId         string                 `protobuf:"bytes,1,opt,name=study_id,json=studyId,proto3" json:"study_id,omitempty"`
	IncludeArchived bool                   `protobuf:"varint,2,opt,name=include_archived,json=includeArchived,proto3" json:"include_archived,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetMaterialTreeRequest) Reset() {
	*x = GetMaterialTreeRequest{}
	mi := &file_wantstudy_v1_study_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMaterialTreeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMaterialTreeRequest) ProtoMessage() {}

func (x *GetMaterialTreeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wantstudy_v1_study_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMaterialTreeRequest.ProtoReflect.Descriptor instead.
func (*GetMaterialTreeRequest) Descriptor() ([]byte, []int) {
	return file_wantstudy_v1_study_proto_rawDescGZIP(), []int{17}
}

func (x *GetMaterialTreeRequest) GetStudyId() string {
	if x != nil {
		return x.StudyId
	}
	return ""
}

func (x *GetMaterialTreeRequest) GetIncludeArchived() bool {
	if x != nil {
		return x.IncludeArchived
	}
	return false
}

type SourceNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        *LearningSource        `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Sections      []*Section             `protobuf:"bytes,2,rep,name=sections,proto3" json:"sections,omitempty"`
	Lessons       []*Lesson              `protobuf:"bytes,3,rep,name=lessons,proto3" json:"lessons,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceNode) Reset() {
	*x = SourceNode{}
	mi := &file_wantstudy_v1_study_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceNode) ProtoMessage() {}

func (x *SourceNode) ProtoReflect() protoreflect.Message {
	mi := &file_wantstudy_v1_study_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceNode.ProtoReflect.Descriptor instead.
func (*SourceNode) Descriptor() ([]byte, []int) {
	return file_wantstudy_v1_study_proto_rawDescGZIP(), []int{18}
}

func (x *SourceNode) GetSource() *LearningSource {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *SourceNode) GetSections() []*Section {
	if x != nil {
		return x.Sections
	}
	return nil
}

func (x *SourceNode) GetLessons() []*Lesson {
	if x != nil {
		return x.Lessons
	}
	return nil
}

type MaterialTree struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Study         *Study                 `protobuf:"bytes,1,opt,name=study,proto3" json:"study,omitempty"`
	Sources       []*SourceNode          `protobuf:"bytes,2,rep,name=sources,proto3" json:"sources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MaterialTree) Reset() {
	*x = MaterialTree{}
	mi := &file_wantstudy_v1_study_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaterialTree) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaterialTree) ProtoMessage() {}

func (x *MaterialTree) ProtoReflect() protoreflect.Message {
	mi := &file_wantstudy_v1_study_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaterialTree.ProtoReflect.Descriptor instead.
func (*MaterialTree) Descriptor() ([]byte, []int) {
	return file_wantstudy_v1_study_proto_rawDescGZIP(), []int{19}
}

func (x *MaterialTree) GetStudy() *Study {
	if x != nil {
		return x.Study
	}
	return nil
}

func (x *MaterialTree) GetSources() []*SourceNode {
	if x != nil {
		return x.Sources
	}
	return nil
}

type ReorderItem struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Position        int32                  `protobuf:"varint,2,opt,name=position,proto3" json:"position,omitempty"`
	ExpectedVersion int64                  `protobuf:"varint,3,opt,name=expected_version,json=expectedVersion,proto3" json:"expected_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReorderItem) Reset() {
	*x = ReorderItem{}
	mi := &file_wantstudy_v1_study_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReorderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReorderItem) ProtoMessage() {}

func (x *ReorderItem) ProtoReflect() protoreflect.Message {
	mi := &file_wantstudy_v1_study_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReorderItem.ProtoReflect.Descriptor instead.
func (*ReorderItem) Descriptor() ([]byte, []int) {
	return file_wantstudy_v1_study_proto_rawDescGZIP(), []int{20}
}

func (x *ReorderItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ReorderItem) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *ReorderItem) GetExpectedVersion() int64 {
	if x != nil {
		return x.ExpectedVersion
	}
	return 0
}

type ReorderMaterialRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudyId       string                 `protobuf:"bytes,1,opt,name=study_id,json=studyId,proto3" json:"study_id,omitempty"`
	Sources       []*ReorderItem         `protobuf:"bytes,2,rep,name=sources,proto3" json:"sources,omitempty"`
	Sections      []*ReorderItem         `protobuf:"bytes,3,rep,name=sections,proto3" json:"sections,omitempty"`
	Lessons       []*ReorderItem         `protobuf:"bytes,4,rep,name=lessons,proto3" json:"lessons,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReorderMaterialRequest) Reset() {
	*x = ReorderMaterialRequest{}
	mi := &file_wantstudy_v1_study_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReorderMaterialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReorderMaterialRequest) ProtoMessage() {}

func (x *ReorderMaterialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wantstudy_v1_study_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReorderMaterialRequest.ProtoReflect.Descriptor instead.
func (*ReorderMaterialRequest) Descriptor() ([]byte, []int) {
	return file_wantstudy_v1_study_proto_rawDescGZIP(), []int{21}
}

func (x *ReorderMaterialRequest) GetStudyId() string {
	if x != nil {
		return x.StudyId
	}
	return ""
}

func (x *ReorderMaterialRequest) GetSources() []*ReorderItem {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *ReorderMaterialRequest) GetSections() []*ReorderItem {
	if x != nil {
		return x.Sections
	}
	return nil
}

func (x *ReorderMaterialRequest) GetLessons() []*ReorderItem {
	if x != nil {
		return x.Lessons
	}
	return nil
}

type GetDashboardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudyId       string                 `protobuf:"bytes,1,opt,name=study_id,json=studyId,proto3" json:"study_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDashboardRequest) Reset() {
	*x = GetDashboardRequest{}
	mi := &file_wantstudy_v1_study_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDashboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDashboardRequest) ProtoMessage() {}

func (x *GetDashboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wantstudy_v1_study_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDashboardRequest.ProtoReflect.Descriptor instead.
func (*GetDashboardRequest) Descriptor() ([]byte, []int) {
	return file_wantstudy_v1_study_proto_rawDescGZIP(), []int{22}
}

func (x *GetDashboardRequest) GetStudyId() string {
	if x != nil {
		return x.StudyId
	}
	return ""
}

type Progress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Completed     int32                  `protobuf:"varint,1,opt,name=completed,proto3" json:"completed,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Progress) Reset() {
	*x = Progress{}
	mi := &file_wantstudy_v1_study_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Progress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Progress) ProtoMessage() {}

func (x *Progress) ProtoReflect() protoreflect.Message {
	mi := &file_wantstudy_v1_study_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Progress.ProtoReflect.Descriptor instead.
func (*Progress) Descriptor() ([]byte, []int) {
	return file_wantstudy_v1_study_proto_rawDescGZIP(), []int{23}
}

func (x *Progress) GetCompleted() int32 {
	if x != nil {
		return x.Completed
	}
	return 0
}

func (x *Progress) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type StatusCount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        LessonStatus           `protobuf:"varint,1,opt,name=status,proto3,enum=wantstudy.v1.LessonStatus" json:"status,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusCount) Reset() {
	*x = StatusCount{}
	mi := &file_wantstudy_v1_study_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusCount) ProtoMessage() {}

func (x *StatusCount) ProtoReflect() protoreflect.Message {
	mi := &file_wantstudy_v1_study_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusCount.ProtoReflect.Descriptor instead.
func (*StatusCount) Descriptor() ([]byte, []int) {
	return file_wantstudy_v1_study_proto_rawDescGZIP(), []int{24}
}

func (x *StatusCount) GetStatus() LessonStatus {
	if x != nil {
		return x.Status
	}
	return LessonStatus_LESSON_STATUS_UNSPECIFIED
}

func (x *StatusCount) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type Dashboard struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Material       *Progress              `protobuf:"bytes,1,opt,name=material,proto3" json:"material,omitempty"`
	Homework       *Progress              `protobuf:"bytes,2,opt,name=homework,proto3" json:"homework,omitempty"`
	LessonStatuses []*StatusCount         `protobuf:"bytes,3,rep,name=lesson_statuses,json=lessonStatuses,proto3" json:"lesson_statuses,omitempty"`
	StudyRevision  int64                  `protobuf:"varint,4,opt,name=study_revision,json=studyRevision,proto3" json:"study_revision,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Dashboard) Reset() {
	*x = Dashboard{}
	mi := &file_wantstudy_v1_study_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dashboard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dashboard) ProtoMessage() {}

func (x *Dashboard) ProtoReflect() protoreflect.Message {
	mi := &file_wantstudy_v1_study_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dashboard.ProtoReflect.Descriptor instead.
func (*Dashboard) Descriptor() ([]byte, []int) {
	return file_wantstudy_v1_study_proto_rawDescGZIP(), []int{25}
}

func (x *Dashboard) GetMaterial() *Progress {
	if x != nil {
		return x.Material
	}
	return nil
}

func (x *Dashboard) GetHomework() *Progress {
	if x != nil {
		return x.Homework
	}
	return nil
}

func (x *Dashboard) GetLessonStatuses() []*StatusCount {
	if x != nil {
		return x.LessonStatuses
	}
	return nil
}

func (x *Dashboard) GetStudyRevision() int64 {
	if x != nil {
		return x.StudyRevision
	}
	return 0
}

var File_wantstudy_v1_study_proto protoreflect.FileDescriptor

const file_wantstudy_v1_study_proto_rawDesc = "" +
	"\n" +
	"\x18wantstudy/v1/study.proto\x12\fwantstudy.v1\"\xc4\x02\n" +
	"\x05Study\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04goal\x18\x03 \x01(\tR\x04goal\x122\n" +
	"\x15local_repository_path\x18\x04 \x01(\tR\x13localRepositoryPath\x12\x18\n" +
	"\aversion\x18\x05 \x01(\x03R\aversion\x12)\n" +
	"\x10content_revision\x18\x06 \x01(\x03R\x0fcontentRevision\x12\x1a\n" +
	"\barchived\x18\a \x01(\bR\barchived\x125\n" +
	"\x17created_at_epoch_millis\x18\b \x01(\x03R\x14createdAtEpochMillis\x125\n" +
	"\x17updated_at_epoch_millis\x18\t \x01(\x03R\x14updatedAtEpochMillis\"\xa4\x02\n" +
	"\x0eLearningSource\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bstudy_id\x18\x02 \x01(\tR\astudyId\x124\n" +
	"\x04type\x18\x03 \x01(\x0e2 .wantstudy.v1.LearningSourceTypeR\x04type\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x16\n" +
	"\x06author\x18\x05 \x01(\tR\x06author\x12\x10\n" +
	"\x03url\x18\x06 \x01(\tR\x03url\x12\x1f\n" +
	"\vexport_slug\x18\a \x01(\tR\n" +
	"exportSlug\x12\x1a\n" +
	"\bposition\x18\b \x01(\x05R\bposition\x12\x18\n" +
	"\aversion\x18\t \x01(\x03R\aversion\x12\x1a\n" +
	"\barchived\x18\n" +
	" \x01(\bR\barchived\"\xb9\x01\n" +
	"\aSection\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bstudy_id\x18\x02 \x01(\tR\astudyId\x12\x1b\n" +
	"\tsource_id\x18\x03 \x01(\tR\bsourceId\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x1a\n" +
	"\bposition\x18\x05 \x01(\x05R\bposition\x12\x18\n" +
	"\aversion\x18\x06 \x01(\x03R\aversion\x12\x1a\n" +
	"\barchived\x18\a \x01(\bR\barchived\"\xae\x04\n" +
	"\x06Lesson\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bstudy_id\x18\x02 \x01(\tR\astudyId\x12\x1b\n" +
	"\tsource_id\x18\x03 \x01(\tR\bsourceId\x12\"\n" +
	"\n" +
	"section_id\x18\x04 \x01(\tH\x00R\tsectionId\x88\x01\x01\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12\x10\n" +
	"\x03url\x18\x06 \x01(\tR\x03url\x12'\n" +
	"\x0fsource_position\x18\a \x01(\tR\x0esourcePosition\x12\x1f\n" +
	"\vexport_slug\x18\b \x01(\tR\n" +
	"exportSlug\x12\x1a\n" +
	"\bposition\x18\t \x01(\x05R\bposition\x122\n" +
	"\x06status\x18\n" +
	" \x01(\x0e2\x1a.wantstudy.v1.LessonStatusR\x06status\x12:\n" +
	"\x17started_at_epoch_millis\x18\v \x01(\x03H\x01R\x14startedAtEpochMillis\x88\x01\x01\x12<\n" +
	"\x18mastered_at_epoch_millis\x18\f \x01(\x03H\x02R\x15masteredAtEpochMillis\x88\x01\x01\x12\x18\n" +
	"\aversion\x18\r \x01(\x03R\aversion\x12\x1a\n" +
	"\barchived\x18\x0e \x01(\bR\barchivedB\r\n" +
	"\v_section_idB\x1a\n" +
	"\x18_started_at_epoch_millisB\x1b\n" +
	"\x19_mastered_at_epoch_millis\"\x82\x01\n" +
	"\x12CreateStudyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04goal\x18\x03 \x01(\tR\x04goal\x122\n" +
	"\x15local_repository_path\x18\x04 \x01(\tR\x13localRepositoryPath\"!\n" +
	"\x0fGetStudyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"?\n" +
	"\x12ListStudiesRequest\x12)\n" +
	"\x10include_archived\x18\x01 \x01(\bR\x0fincludeArchived\"D\n" +
	"\x13ListStudiesResponse\x12-\n" +
	"\astudies\x18\x01 \x03(\v2\x13.wantstudy.v1.StudyR\astudies\"\xad\x01\n" +
	"\x12UpdateStudyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04goal\x18\x03 \x01(\tR\x04goal\x122\n" +
	"\x15local_repository_path\x18\x04 \x01(\tR\x13localRepositoryPath\x12)\n" +
	"\x10expected_version\x18\x05 \x01(\x03R\x0fexpectedVersion\"Q\n" +
	"\x14ChangeArchiveRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12)\n" +
	"\x10expected_version\x18\x02 \x01(\x03R\x0fexpectedVersion\"\xfb\x01\n" +
	"\x1bCreateLearningSourceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bstudy_id\x18\x02 \x01(\tR\astudyId\x124\n" +
	"\x04type\x18\x03 \x01(\x0e2 .wantstudy.v1.LearningSourceTypeR\x04type\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x16\n" +
	"\x06author\x18\x05 \x01(\tR\x06author\x12\x10\n" +
	"\x03url\x18\x06 \x01(\tR\x03url\x12\x1f\n" +
	"\vexport_slug\x18\a \x01(\tR\n" +
	"exportSlug\x12\x1a\n" +
	"\bposition\x18\b \x01(\x05R\bposition\"~\n" +
	"\x1bUpdateLearningSourceRequest\x124\n" +
	"\x06source\x18\x01 \x01(\v2\x1c.wantstudy.v1.LearningSourceR\x06source\x12)\n" +
	"\x10expected_version\x18\x02 \x01(\x03R\x0fexpectedVersion\"\x90\x01\n" +
	"\x14CreateSectionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bstudy_id\x18\x02 \x01(\tR\astudyId\x12\x1b\n" +
	"\tsource_id\x18\x03 \x01(\tR\bsourceId\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x1a\n" +
	"\bposition\x18\x05 \x01(\x05R\bposition\"r\n" +
	"\x14UpdateSectionRequest\x12/\n" +
	"\asection\x18\x01 \x01(\v2\x15.wantstudy.v1.SectionR\asection\x12)\n" +
	"\x10expected_version\x18\x02 \x01(\x03R\x0fexpectedVersion\"\xd2\x02\n" +
	"\x13CreateLessonRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bstudy_id\x18\x02 \x01(\tR\astudyId\x12\x1b\n" +
	"\tsource_id\x18\x03 \x01(\tR\bsourceId\x12\"\n" +
	"\n" +
	"section_id\x18\x04 \x01(\tH\x00R\tsectionId\x88\x01\x01\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12\x10\n" +
	"\x03url\x18\x06 \x01(\tR\x03url\x12'\n" +
	"\x0fsource_position\x18\a \x01(\tR\x0esourcePosition\x12\x1f\n" +
	"\vexport_slug\x18\b \x01(\tR\n" +
	"exportSlug\x12\x1a\n" +
	"\bposition\x18\t \x01(\x05R\bposition\x122\n" +
	"\x06status\x18\n" +
	" \x01(\x0e2\x1a.wantstudy.v1.LessonStatusR\x06statusB\r\n" +
	"\v_section_id\"n\n" +
	"\x13UpdateLessonRequest\x12,\n" +
	"\x06lesson\x18\x01 \x01(\v2\x14.wantstudy.v1.LessonR\x06lesson\x12)\n" +
	"\x10expected_version\x18\x02 \x01(\x03R\x0fexpectedVersion\"\xc6\x01\n" +
	"\x19ChangeLessonStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x122\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1a.wantstudy.v1.LessonStatusR\x06status\x12)\n" +
	"\x10expected_version\x18\x03 \x01(\x03R\x0fexpectedVersion\x12:\n" +
	"\x19acknowledge_open_homework\x18\x04 \x01(\bR\x17acknowledgeOpenHomework\"^\n" +
	"\x16GetMaterialTreeRequest\x12\x19\n" +
	"\bstudy_id\x18\x01 \x01(\tR\astudyId\x12)\n" +
	"\x10include_archived\x18\x02 \x01(\bR\x0fincludeArchived\"\xa5\x01\n" +
	"\n" +
	"SourceNode\x124\n" +
	"\x06source\x18\x01 \x01(\v2\x1c.wantstudy.v1.LearningSourceR\x06source\x121\n" +
	"\bsections\x18\x02 \x03(\v2\x15.wantstudy.v1.SectionR\bsections\x12.\n" +
	"\alessons\x18\x03 \x03(\v2\x14.wantstudy.v1.LessonR\alessons\"m\n" +
	"\fMaterialTree\x12)\n" +
	"\x05study\x18\x01 \x01(\v2\x13.wantstudy.v1.StudyR\x05study\x122\n" +
	"\asources\x18\x02 \x03(\v2\x18.wantstudy.v1.SourceNodeR\asources\"d\n" +
	"\vReorderItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bposition\x18\x02 \x01(\x05R\bposition\x12)\n" +
	"\x10expected_version\x18\x03 \x01(\x03R\x0fexpectedVersion\"\xd4\x01\n" +
	"\x16ReorderMaterialRequest\x12\x19\n" +
	"\bstudy_id\x18\x01 \x01(\tR\astudyId\x123\n" +
	"\asources\x18\x02 \x03(\v2\x19.wantstudy.v1.ReorderItemR\asources\x125\n" +
	"\bsections\x18\x03 \x03(\v2\x19.wantstudy.v1.ReorderItemR\bsections\x123\n" +
	"\alessons\x18\x04 \x03(\v2\x19.wantstudy.v1.ReorderItemR\alessons\"0\n" +
	"\x13GetDashboardRequest\x12\x19\n" +
	"\bstudy_id\x18\x01 \x01(\tR\astudyId\">\n" +
	"\bProgress\x12\x1c\n" +
	"\tcompleted\x18\x01 \x01(\x05R\tcompleted\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"W\n" +
	"\vStatusCount\x122\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1a.wantstudy.v1.LessonStatusR\x06status\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"\xde\x01\n" +
	"\tDashboard\x122\n" +
	"\bmaterial\x18\x01 \x01(\v2\x16.wantstudy.v1.ProgressR\bmaterial\x122\n" +
	"\bhomework\x18\x02 \x01(\v2\x16.wantstudy.v1.ProgressR\bhomework\x12B\n" +
	"\x0flesson_statuses\x18\x03 \x03(\v2\x19.wantstudy.v1.StatusCountR\x0elessonStatuses\x12%\n" +
	"\x0estudy_revision\x18\x04 \x01(\x03R\rstudyRevision*\xdc\x01\n" +
	"\x12LearningSourceType\x12$\n" +
	" LEARNING_SOURCE_TYPE_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bLEARNING_SOURCE_TYPE_COURSE\x10\x01\x12\x1d\n" +
	"\x19LEARNING_SOURCE_TYPE_BOOK\x10\x02\x12 \n" +
	"\x1cLEARNING_SOURCE_TYPE_ARTICLE\x10\x03\x12\x1e\n" +
	"\x1aLEARNING_SOURCE_TYPE_VIDEO\x10\x04\x12\x1e\n" +
	"\x1aLEARNING_SOURCE_TYPE_OTHER\x10\x05*\x9c\x01\n" +
	"\fLessonStatus\x12\x1d\n" +
	"\x19LESSON_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15LESSON_STATUS_PLANNED\x10\x01\x12\x1a\n" +
	"\x16LESSON_STATUS_STUDYING\x10\x02\x12\x1a\n" +
	"\x16LESSON_STATUS_HOMEWORK\x10\x03\x12\x1a\n" +
	"\x16LESSON_STATUS_MASTERED\x10\x042\xe4\r\n" +
	"\x13StudyCatalogService\x12D\n" +
	"\vCreateStudy\x12 .wantstudy.v1.CreateStudyRequest\x1a\x13.wantstudy.v1.Study\x12>\n" +
	"\bGetStudy\x12\x1d.wantstudy.v1.GetStudyRequest\x1a\x13.wantstudy.v1.Study\x12R\n" +
	"\vListStudies\x12 .wantstudy.v1.ListStudiesRequest\x1a!.wantstudy.v1.ListStudiesResponse\x12D\n" +
	"\vUpdateStudy\x12 .wantstudy.v1.UpdateStudyRequest\x1a\x13.wantstudy.v1.Study\x12G\n" +
	"\fArchiveStudy\x12\".wantstudy.v1.ChangeArchiveRequest\x1a\x13.wantstudy.v1.Study\x12G\n" +
	"\fRestoreStudy\x12\".wantstudy.v1.ChangeArchiveRequest\x1a\x13.wantstudy.v1.Study\x12_\n" +
	"\x14CreateLearningSource\x12).wantstudy.v1.CreateLearningSourceRequest\x1a\x1c.wantstudy.v1.LearningSource\x12_\n" +
	"\x14UpdateLearningSource\x12).wantstudy.v1.UpdateLearningSourceRequest\x1a\x1c.wantstudy.v1.LearningSource\x12Y\n" +
	"\x15ArchiveLearningSource\x12\".wantstudy.v1.ChangeArchiveRequest\x1a\x1c.wantstudy.v1.LearningSource\x12Y\n" +
	"\x15RestoreLearningSource\x12\".wantstudy.v1.ChangeArchiveRequest\x1a\x1c.wantstudy.v1.LearningSource\x12J\n" +
	"\rCreateSection\x12\".wantstudy.v1.CreateSectionRequest\x1a\x15.wantstudy.v1.Section\x12J\n" +
	"\rUpdateSection\x12\".wantstudy.v1.UpdateSectionRequest\x1a\x15.wantstudy.v1.Section\x12K\n" +
	"\x0eArchiveSection\x12\".wantstudy.v1.ChangeArchiveRequest\x1a\x15.wantstudy.v1.Section\x12K\n" +
	"\x0eRestoreSection\x12\".wantstudy.v1.ChangeArchiveRequest\x1a\x15.wantstudy.v1.Section\x12G\n" +
	"\fCreateLesson\x12!.wantstudy.v1.CreateLessonRequest\x1a\x14.wantstudy.v1.Lesson\x12G\n" +
	"\fUpdateLesson\x12!.wantstudy.v1.UpdateLessonRequest\x1a\x14.wantstudy.v1.Lesson\x12I\n" +
	"\rArchiveLesson\x12\".wantstudy.v1.ChangeArchiveRequest\x1a\x14.wantstudy.v1.Lesson\x12I\n" +
	"\rRestoreLesson\x12\".wantstudy.v1.ChangeArchiveRequest\x1a\x14.wantstudy.v1.Lesson\x12S\n" +
	"\x12ChangeLessonStatus\x12'.wantstudy.v1.ChangeLessonStatusRequest\x1a\x14.wantstudy.v1.Lesson\x12S\n" +
	"\x0fGetMaterialTree\x12$.wantstudy.v1.GetMaterialTreeRequest\x1a\x1a.wantstudy.v1.MaterialTree\x12S\n" +
	"\x0fReorderMaterial\x12$.wantstudy.v1.ReorderMaterialRequest\x1a\x1a.wantstudy.v1.MaterialTree\x12J\n" +
	"\fGetDashboard\x12!.wantstudy.v1.GetDashboardRequest\x1a\x17.wantstudy.v1.DashboardBSZQgithub.com/pchkauu/want-study/service/api/internal/proto/wantstudy/v1;wantstudyv1b\x06proto3"

var (
	file_wantstudy_v1_study_proto_rawDescOnce sync.Once
	file_wantstudy_v1_study_proto_rawDescData []byte
)

func file_wantstudy_v1_study_proto_rawDescGZIP() []byte {
	file_wantstudy_v1_study_proto_rawDescOnce.Do(func() {
		file_wantstudy_v1_study_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wantstudy_v1_study_proto_rawDesc), len(file_wantstudy_v1_study_proto_rawDesc)))
	})
	return file_wantstudy_v1_study_proto_rawDescData
}

var file_wantstudy_v1_study_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_wantstudy_v1_study_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_wantstudy_v1_study_proto_goTypes = []any{
	(LearningSourceType)(0),             // 0: wantstudy.v1.LearningSourceType
	(LessonStatus)(0),                   // 1: wantstudy.v1.LessonStatus
	(*Study)(nil),                       // 2: wantstudy.v1.Study
	(*LearningSource)(nil),              // 3: wantstudy.v1.LearningSource
	(*Section)(nil),                     // 4: wantstudy.v1.Section
	(*Lesson)(nil),                      // 5: wantstudy.v1.Lesson
	(*CreateStudyRequest)(nil),          // 6: wantstudy.v1.CreateStudyRequest
	(*GetStudyRequest)(nil),             // 7: wantstudy.v1.GetStudyRequest
	(*ListStudiesRequest)(nil),          // 8: wantstudy.v1.ListStudiesRequest
	(*ListStudiesResponse)(nil),         // 9: wantstudy.v1.ListStudiesResponse
	(*UpdateStudyRequest)(nil),          // 10: wantstudy.v1.UpdateStudyRequest
	(*ChangeArchiveRequest)(nil),        // 11: wantstudy.v1.ChangeArchiveRequest
	(*CreateLearningSourceRequest)(nil), // 12: wantstudy.v1.CreateLearningSourceRequest
	(*UpdateLearningSourceRequest)(nil), // 13: wantstudy.v1.UpdateLearningSourceRequest
	(*CreateSectionRequest)(nil),        // 14: wantstudy.v1.CreateSectionRequest
	(*UpdateSectionRequest)(nil),        // 15: wantstudy.v1.UpdateSectionRequest
	(*CreateLessonRequest)(nil),         // 16: wantstudy.v1.CreateLessonRequest
	(*UpdateLessonRequest)(nil),         // 17: wantstudy.v1.UpdateLessonRequest
	(*ChangeLessonStatusRequest)(nil),   // 18: wantstudy.v1.ChangeLessonStatusRequest
	(*GetMaterialTreeRequest)(nil),      // 19: wantstudy.v1.GetMaterialTreeRequest
	(*SourceNode)(nil),                  // 20: wantstudy.v1.SourceNode
	(*MaterialTree)(nil),                // 21: wantstudy.v1.MaterialTree
	(*ReorderItem)(nil),                 // 22: wantstudy.v1.ReorderItem
	(*ReorderMaterialRequest)(nil),      // 23: wantstudy.v1.ReorderMaterialRequest
	(*GetDashboardRequest)(nil),         // 24: wantstudy.v1.GetDashboardRequest
	(*Progress)(nil),                    // 25: wantstudy.v1.Progress
	(*StatusCount)(nil),                 // 26: wantstudy.v1.StatusCount
	(*Dashboard)(nil),                   // 27: wantstudy.v1.Dashboard
}
var file_wantstudy_v1_study_proto_depIdxs = []int32{
	0,  // 0: wantstudy.v1.LearningSource.type:type_name -> wantstudy.v1.LearningSourceType
	1,  // 1: wantstudy.v1.Lesson.status:type_name -> wantstudy.v1.LessonStatus
	2,  // 2: wantstudy.v1.ListStudiesResponse.studies:type_name -> wantstudy.v1.Study
	0,  // 3: wantstudy.v1.CreateLearningSourceRequest.type:type_name -> wantstudy.v1.LearningSourceType
	3,  // 4: wantstudy.v1.UpdateLearningSourceRequest.source:type_name -> wantstudy.v1.LearningSource
	4,  // 5: wantstudy.v1.UpdateSectionRequest.section:type_name -> wantstudy.v1.Section
	1,  // 6: wantstudy.v1.CreateLessonRequest.status:type_name -> wantstudy.v1.LessonStatus
	5,  // 7: wantstudy.v1.UpdateLessonRequest.lesson:type_name -> wantstudy.v1.Lesson
	1,  // 8: wantstudy.v1.ChangeLessonStatusRequest.status:type_name -> wantstudy.v1.LessonStatus
	3,  // 9: wantstudy.v1.SourceNode.source:type_name -> wantstudy.v1.LearningSource
	4,  // 10: wantstudy.v1.SourceNode.sections:type_name -> wantstudy.v1.Section
	5,  // 11: wantstudy.v1.SourceNode.lessons:type_name -> wantstudy.v1.Lesson
	2,  // 12: wantstudy.v1.MaterialTree.study:type_name -> wantstudy.v1.Study
	20, // 13: wantstudy.v1.MaterialTree.sources:type_name -> wantstudy.v1.SourceNode
	22, // 14: wantstudy.v1.ReorderMaterialRequest.sources:type_name -> wantstudy.v1.ReorderItem
	22, // 15: wantstudy.v1.ReorderMaterialRequest.sections:type_name -> wantstudy.v1.ReorderItem
	22, // 16: wantstudy.v1.ReorderMaterialRequest.lessons:type_name -> wantstudy.v1.ReorderItem
	1,  // 17: wantstudy.v1.StatusCount.status:type_name -> wantstudy.v1.LessonStatus
	25, // 18: wantstudy.v1.Dashboard.material:type_name -> wantstudy.v1.Progress
	25, // 19: wantstudy.v1.Dashboard.homework:type_name -> wantstudy.v1.Progress
	26, // 20: wantstudy.v1.Dashboard.lesson_statuses:type_name -> wantstudy.v1.StatusCount
	6,  // 21: wantstudy.v1.StudyCatalogService.CreateStudy:input_type -> wantstudy.v1.CreateStudyRequest
	7,  // 22: wantstudy.v1.StudyCatalogService.GetStudy:input_type -> wantstudy.v1.GetStudyRequest
	8,  // 23: wantstudy.v1.StudyCatalogService.ListStudies:input_type -> wantstudy.v1.ListStudiesRequest
	10, // 24: wantstudy.v1.StudyCatalogService.UpdateStudy:input_type -> wantstudy.v1.UpdateStudyRequest
	11, // 25: wantstudy.v1.StudyCatalogService.ArchiveStudy:input_type -> wantstudy.v1.ChangeArchiveRequest
	11, // 26: wantstudy.v1.StudyCatalogService.RestoreStudy:input_type -> wantstudy.v1.ChangeArchiveRequest
	12, // 27: wantstudy.v1.StudyCatalogService.CreateLearningSource:input_type -> wantstudy.v1.CreateLearningSourceRequest
	13, // 28: wantstudy.v1.StudyCatalogService.UpdateLearningSource:input_type -> wantstudy.v1.UpdateLearningSourceRequest
	11, // 29: wantstudy.v1.StudyCatalogService.ArchiveLearningSource:input_type -> wantstudy.v1.ChangeArchiveRequest
	11, // 30: wantstudy.v1.StudyCatalogService.RestoreLearningSource:input_type -> wantstudy.v1.ChangeArchiveRequest
	14, // 31: wantstudy.v1.StudyCatalogService.CreateSection:input_type -> wantstudy.v1.CreateSectionRequest
	15, // 32: wantstudy.v1.StudyCatalogService.UpdateSection:input_type -> wantstudy.v1.UpdateSectionRequest
	11, // 33: wantstudy.v1.StudyCatalogService.ArchiveSection:input_type -> wantstudy.v1.ChangeArchiveRequest
	11, // 34: wantstudy.v1.StudyCatalogService.RestoreSection:input_type -> wantstudy.v1.ChangeArchiveRequest
	16, // 35: wantstudy.v1.StudyCatalogService.CreateLesson:input_type -> wantstudy.v1.CreateLessonRequest
	17, // 36: wantstudy.v1.StudyCatalogService.UpdateLesson:input_type -> wantstudy.v1.UpdateLessonRequest
	11, // 37: wantstudy.v1.StudyCatalogService.ArchiveLesson:input_type -> wantstudy.v1.ChangeArchiveRequest
	11, // 38: wantstudy.v1.StudyCatalogService.RestoreLesson:input_type -> wantstudy.v1.ChangeArchiveRequest
	18, // 39: wantstudy.v1.StudyCatalogService.ChangeLessonStatus:input_type -> wantstudy.v1.ChangeLessonStatusRequest
	19, // 40: wantstudy.v1.StudyCatalogService.GetMaterialTree:input_type -> wantstudy.v1.GetMaterialTreeRequest
	23, // 41: wantstudy.v1.StudyCatalogService.ReorderMaterial:input_type -> wantstudy.v1.ReorderMaterialRequest
	24, // 42: wantstudy.v1.StudyCatalogService.GetDashboard:input_type -> wantstudy.v1.GetDashboardRequest
	2,  // 43: wantstudy.v1.StudyCatalogService.CreateStudy:output_type -> wantstudy.v1.Study
	2,  // 44: wantstudy.v1.StudyCatalogService.GetStudy:output_type -> wantstudy.v1.Study
	9,  // 45: wantstudy.v1.StudyCatalogService.ListStudies:output_type -> wantstudy.v1.ListStudiesResponse
	2,  // 46: wantstudy.v1.StudyCatalogService.UpdateStudy:output_type -> wantstudy.v1.Study
	2,  // 47: wantstudy.v1.StudyCatalogService.ArchiveStudy:output_type -> wantstudy.v1.Study
	2,  // 48: wantstudy.v1.StudyCatalogService.RestoreStudy:output_type -> wantstudy.v1.Study
	3,  // 49: wantstudy.v1.StudyCatalogService.CreateLearningSource:output_type -> wantstudy.v1.LearningSource
	3,  // 50: wantstudy.v1.StudyCatalogService.UpdateLearningSource:output_type -> wantstudy.v1.LearningSource
	3,  // 51: wantstudy.v1.StudyCatalogService.ArchiveLearningSource:output_type -> wantstudy.v1.LearningSource
	3,  // 52: wantstudy.v1.StudyCatalogService.RestoreLearningSource:output_type -> wantstudy.v1.LearningSource
	4,  // 53: wantstudy.v1.StudyCatalogService.CreateSection:output_type -> wantstudy.v1.Section
	4,  // 54: wantstudy.v1.StudyCatalogService.UpdateSection:output_type -> wantstudy.v1.Section
	4,  // 55: wantstudy.v1.StudyCatalogService.ArchiveSection:output_type -> wantstudy.v1.Section
	4,  // 56: wantstudy.v1.StudyCatalogService.RestoreSection:output_type -> wantstudy.v1.Section
	5,  // 57: wantstudy.v1.StudyCatalogService.CreateLesson:output_type -> wantstudy.v1.Lesson
	5,  // 58: wantstudy.v1.StudyCatalogService.UpdateLesson:output_type -> wantstudy.v1.Lesson
	5,  // 59: wantstudy.v1.StudyCatalogService.ArchiveLesson:output_type -> wantstudy.v1.Lesson
	5,  // 60: wantstudy.v1.StudyCatalogService.RestoreLesson:output_type -> wantstudy.v1.Lesson
	5,  // 61: wantstudy.v1.StudyCatalogService.ChangeLessonStatus:output_type -> wantstudy.v1.Lesson
	21, // 62: wantstudy.v1.StudyCatalogService.GetMaterialTree:output_type -> wantstudy.v1.MaterialTree
	21, // 63: wantstudy.v1.StudyCatalogService.ReorderMaterial:output_type -> wantstudy.v1.MaterialTree
	27, // 64: wantstudy.v1.StudyCatalogService.GetDashboard:output_type -> wantstudy.v1.Dashboard
	43, // [43:65] is the sub-list for method output_type
	21, // [21:43] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_wantstudy_v1_study_proto_init() }
func file_wantstudy_v1_study_proto_init() {
	if File_wantstudy_v1_study_proto != nil {
		return
	}
	file_wantstudy_v1_study_proto_msgTypes[3].OneofWrappers = []any{}
	file_wantstudy_v1_study_proto_msgTypes[14].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wantstudy_v1_study_proto_rawDesc), len(file_wantstudy_v1_study_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wantstudy_v1_study_proto_goTypes,
		DependencyIndexes: file_wantstudy_v1_study_proto_depIdxs,
		EnumInfos:         file_wantstudy_v1_study_proto_enumTypes,
		MessageInfos:      file_wantstudy_v1_study_proto_msgTypes,
	}.Build()
	File_wantstudy_v1_study_proto = out.File
	file_wantstudy_v1_study_proto_goTypes = nil
	file_wantstudy_v1_study_proto_depIdxs = nil
}
